### ISSUE TITLE
Error when attempting test with PhantomJS: ClassNotFound

### ISSUE THREAD

**Issue by erquhart** [galenframework/galen#195]
Getting the following error whenever attempting to test with PhantomJS:

```
java.lang.NoClassDefFoundError: org/openqa/selenium/browserlaunchers/Proxies
        at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:178)
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:99)
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:89)
        at net.mindengine.galen.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:95)
        at net.mindengine.galen.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:61)
        at net.mindengine.galen.utils.GalenUtils.createDriver(GalenUtils.java:246)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at org.mozilla.javascript.gen._cmd__17._c_createDriver_1(<cmd>:32)
        at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen.c__Users_milwa_000_cybercare_projects_charter_charter_net_pages_galen_components____init_js_21._c_openDriver_1(c:\Users\milwa_000\cybercare\projects\charter\charter-net-pages\galen\components\..\init.js:264)
        at org.mozilla.javascript.gen.c__Users_milwa_000_cybercare_projects_charter_charter_net_pages_galen_components____init_js_21.call(c:\Users\milwa_000\cybercare\projects\charter\charter-net-pages\galen\components\..\init.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen.c__Users_milwa_000_cybercare_projects_charter_charter_net_pages_galen_components____init_js_21._c_anonymous_4(c:\Users\milwa_000\cybercare\projects\charter\charter-net-pages\galen\components\..\init.js:288)
        at org.mozilla.javascript.gen.c__Users_milwa_000_cybercare_projects_charter_charter_net_pages_galen_components____init_js_21.call(c:\Users\milwa_000\cybercare\projects\charter\charter-net-pages\galen\components\..\init.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at org.mozilla.javascript.gen._cmd__16._c_invokeFunc_20(<cmd>:243)
        at org.mozilla.javascript.gen._cmd__16.call(<cmd>)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen._cmd__16._c_anonymous_17(<cmd>:205)
        at org.mozilla.javascript.gen._cmd__16.call(<cmd>)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen._cmd__16.call(<cmd>)
        at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:603)
        at org.mozilla.javascript.JavaAdapter.access$000(JavaAdapter.java:15)
        at org.mozilla.javascript.JavaAdapter$1.run(JavaAdapter.java:583)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:580)
        at adapter2.execute(<adapter>)
        at net.mindengine.galen.TestRunnable.runTest(TestRunnable.java:63)
        at net.mindengine.galen.TestRunnable.run(TestRunnable.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.browserlaunchers.Proxies
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 45 more
```

**Comment by ishubin** [comment]
That's weird. I thought I have checked it. Will test it more thoroughly again.

**Comment by erquhart** [comment]
@ishubin it may be related to this Selenium issue: https://code.google.com/p/selenium/issues/detail?id=8088

**Comment by ishubin** [comment]
Thanks for the link.
This means that we need to wait for https://github.com/detro/ghostdriver/issues/397 to go live. Or I might just add a dependency from this comment https://github.com/detro/ghostdriver/issues/397#issuecomment-65539540

**Comment by Menthalion** [comment]
Another workaround would be to use selenium 2.44 and include the following java class in your program:

    package org.openqa.selenium.browserlaunchers;

            import org.openqa.selenium.Capabilities;
            import org.openqa.selenium.Proxy;

    public class Proxies {
        public static Proxy extractProxy(Capabilities capabilities) {
            return Proxy.extractFrom(capabilities);
        }
    }

**Comment by ishubin** [comment]
@Menthalion Thanks for the hint. At the moment I have rolled back to version 2.43 but using the latest selenium-firefox-driver version. The main reason of using selenium 2.44 was the support for latest firefox browser. Still the setup is a bit hacky but at least it works for now.

**Comment by hypery2k** [comment]
I've already updated on my fork to newer selenium and use a patched phantomjs

**Comment by prmichaelsen** [comment]
I also had this issue, and found placing selenium dependencies first in your pom.xml resolves this issue for me
