### ISSUE TITLE
Test errors with release 1.5.1

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#203]
I've run locally some tests and on my private jenkins server: https://martinreinhardt-online.de/jenkins/job/GalenFramework_build/lastBuild/testReport/ I improved all browser tests to easy change to browser to use, see my [fork](https://github.com/hypery2k/galen/tree/release-1.5)

```mvn clean verify -Dwebdriver.chrome.driver=/opt/dev/chromedriver -Dgalen.default.browser=chrome```

I'm getting two failed tests:

```
shouldImport_otherSpecs_fromOtherFiles(net.mindengine.galen.tests.specs.reader.PageSpecsReaderTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: map containing ["header"->ANYTHING]
     but: map was [<content=net.mindengine.galen.specs.page.Locator@32cb636e[locatorType=id,locatorValue=content,corrections=<null>]>]
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at net.mindengine.galen.tests.specs.reader.PageSpecsReaderTest.shouldImport_otherSpecs_fromOtherFiles(PageSpecsReaderTest.java:464)

performsValidation_forMobile_withTwoSections(net.mindengine.galen.tests.selenium.GalenSeleniumTest)  Time elapsed: 0.684 sec  <<< FAILURE!
java.lang.AssertionError: Invokations should
Expected: is "<o header>\n<SpecHeight header>\n</o header>\n<o menu-item-home>\n<SpecHorizontally menu-item-home>\n</o menu-item-home>\n<o menu-item-rss>\n<SpecHorizontally menu-item-rss>\n<SpecNear menu-item-rss>\n</o menu-item-rss>\n"
     but: was "<o header>\n<SpecHeight header>\n<e><msg>\"header\" height is 148px which is not in range of 150 to 185px</msg></e>\n</o header>\n<o menu-item-home>\n<SpecHorizontally menu-item-home>\n</o menu-item-home>\n<o menu-item-rss>\n<SpecHorizontally menu-item-rss>\n<SpecNear menu-item-rss>\n</o menu-item-rss>\n"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at net.mindengine.galen.tests.selenium.GalenSeleniumTest.performsValidation_forMobile_withTwoSections(GalenSeleniumTest.java:142)


Results :

Failed tests:   shouldImport_otherSpecs_fromOtherFiles(net.mindengine.galen.tests.specs.reader.PageSpecsReaderTest): (..)
  performsValidation_forMobile_withTwoSections(net.mindengine.galen.tests.selenium.GalenSeleniumTest): Invokations should(..)

Tests run: 667, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by ishubin** [comment]
Those are unstable tests. I am going to refactor them later.  I did a lot if tests today with version 1.5.1 and it seems to be ok

**Comment by hypery2k** [comment]
ok, I will take a look at these tests. My personal tests with JUnit and TestNG seems good so far. 1.5.1 works for me perfectly with Chrome, Safari and Firefox. Did you pushed 1.5.1 already to maven central?

**Comment by ishubin** [comment]
Not yet. I will push it to central repo later today once I am at my desk

**Comment by ishubin** [comment]
I have released it to central repo
