### ISSUE TITLE
Error making screenshot - Galen 1.5.1

### ISSUE THREAD

**Issue by kreatific** [galenframework/galen#211]
Just recently found Galen and I have to thank you for creating an awesome framework.

I updated Galen to 1.5.1 yesterday and when I go to run a "Test Suite" now, I get an "Error making screenshot".

I've added the trace below. Do you need anything else?

Expression node.layoutReport.screenshot is undefined on line 35, column 67 in report-main.
The problematic instruction:
----------
==> ${node.layoutReport.screenshot?html} [on line 35, column 65 in report-main]
 in user-directive report_node [on line 30, column 25 in report-main]
 in user-directive report_node [on line 30, column 25 in report-main]
 in user-directive report_node [on line 120, column 17 in report-main]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression node.layoutReport.screenshot is undefined on line 35, column 67 in
 report-main.
        at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
        at freemarker.core.Expression.getStringValue(Expression.java:118)
        at freemarker.core.Expression.getStringValue(Expression.java:93)
        at freemarker.core.StringBuiltins$StringBuiltIn._getAsTemplateModel(StringBuiltins.java:71)
        at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
        at freemarker.core.Expression.getStringValue(Expression.java:93)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IfBlock.accept(IfBlock.java:82)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.Macro$Context.runMacro(Macro.java:172)
        at freemarker.core.Environment.visit(Environment.java:614)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
        at freemarker.core.Environment.visit(Environment.java:428)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IfBlock.accept(IfBlock.java:82)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.Macro$Context.runMacro(Macro.java:172)
        at freemarker.core.Environment.visit(Environment.java:614)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
        at freemarker.core.Environment.visit(Environment.java:428)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IfBlock.accept(IfBlock.java:82)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.Macro$Context.runMacro(Macro.java:172)
        at freemarker.core.Environment.visit(Environment.java:614)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
        at freemarker.core.Environment.visit(Environment.java:428)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.Environment.process(Environment.java:199)
        at freemarker.template.Template.process(Template.java:259)
        at net.mindengine.galen.reports.HtmlReportBuilder.exportTestReport(HtmlReportBuilder.java:82)
        at net.mindengine.galen.reports.HtmlReportBuilder.build(HtmlReportBuilder.java:62)
        at net.mindengine.galen.GalenMain.createHtmlReport(GalenMain.java:357)
        at net.mindengine.galen.GalenMain.createAllReports(GalenMain.java:351)
        at net.mindengine.galen.GalenMain.runTestsInThreads(GalenMain.java:305)
        at net.mindengine.galen.GalenMain.runTests(GalenMain.java:278)
        at net.mindengine.galen.GalenMain.runTestFiles(GalenMain.java:268)
        at net.mindengine.galen.GalenMain.runTests(GalenMain.java:247)
        at net.mindengine.galen.GalenMain.execute(GalenMain.java:79)
        at net.mindengine.galen.GalenMain.main(GalenMain.java:221)
[main] ERROR net.mindengine.galen.reports.HtmlReportBuilder - Unkown report export

Expression node.layoutReport.screenshot is undefined on line 35, column 67 in report-main.
The problematic instruction:
----------
==> ${node.layoutReport.screenshot?html} [on line 35, column 65 in report-main]
 in user-directive report_node [on line 30, column 25 in report-main]
 in user-directive report_node [on line 30, column 25 in report-main]
 in user-directive report_node [on line 120, column 17 in report-main]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression node.layoutReport.screenshot is undefined on line 35, column 67 in
 report-main.
        at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
        at freemarker.core.Expression.getStringValue(Expression.java:118)
        at freemarker.core.Expression.getStringValue(Expression.java:93)
        at freemarker.core.StringBuiltins$StringBuiltIn._getAsTemplateModel(StringBuiltins.java:71)
        at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
        at freemarker.core.Expression.getStringValue(Expression.java:93)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IfBlock.accept(IfBlock.java:82)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.Macro$Context.runMacro(Macro.java:172)
        at freemarker.core.Environment.visit(Environment.java:614)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
        at freemarker.core.Environment.visit(Environment.java:428)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IfBlock.accept(IfBlock.java:82)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.Macro$Context.runMacro(Macro.java:172)
        at freemarker.core.Environment.visit(Environment.java:614)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
        at freemarker.core.Environment.visit(Environment.java:428)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IfBlock.accept(IfBlock.java:82)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.Macro$Context.runMacro(Macro.java:172)
        at freemarker.core.Environment.visit(Environment.java:614)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
        at freemarker.core.Environment.visit(Environment.java:428)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.MixedContent.accept(MixedContent.java:92)
        at freemarker.core.Environment.visit(Environment.java:221)
        at freemarker.core.Environment.process(Environment.java:199)
        at freemarker.template.Template.process(Template.java:259)
        at net.mindengine.galen.reports.HtmlReportBuilder.exportTestReport(HtmlReportBuilder.java:82)
        at net.mindengine.galen.reports.HtmlReportBuilder.build(HtmlReportBuilder.java:62)
        at net.mindengine.galen.GalenMain.createHtmlReport(GalenMain.java:357)
        at net.mindengine.galen.GalenMain.createAllReports(GalenMain.java:351)
        at net.mindengine.galen.GalenMain.runTestsInThreads(GalenMain.java:305)
        at net.mindengine.galen.GalenMain.runTests(GalenMain.java:278)
        at net.mindengine.galen.GalenMain.runTestFiles(GalenMain.java:268)
        at net.mindengine.galen.GalenMain.runTests(GalenMain.java:247)
        at net.mindengine.galen.GalenMain.execute(GalenMain.java:79)
        at net.mindengine.galen.GalenMain.main(GalenMain.java:221)

**Comment by hypery2k** [comment]
can you sent us your test spec to reproduce the error? How to do you invoke Galen?

**Comment by ishubin** [comment]
The stacktrace is coming from Freemarker because the screenshot is null. It couldn't add the screenshot information to the html report and just failed to generate the report.
First of all I see here a bug: in case the screenshot is not there, it shouldn't crash during report creation.

But the other part which is unclear to me - why did it fail making a screenshot. Do you have any error messages during screenshot creation?

**Comment by hypery2k** [comment]
can you try to latest snapshot, you can use this nexus repo: https://martinreinhardt-online.de/nexus/content/repositories/snapshots/
Latest build you find here: https://martinreinhardt-online.de/nexus/content/repositories/snapshots/net/mindengine/galen/1.5.4-SNAPSHOT/

**Comment by hypery2k** [comment]
I'm currently getting the same error within a customer environment. This happens sporadically. We should  investigate on this. I think it's a threading issue. I'll try to setup some tests, as for us it happens often when using selenium grid

**Comment by ishubin** [comment]
We also use selenium grid and execute galen tests in parallel. We have never reproduced this error. But we are using JavaScript tests. I am not sure if that is the reason

**Comment by hypery2k** [comment]
with the latest 1.6 branch the error isn't existing. I've added a test to ensure that the report is still generating ...
