### ISSUE TITLE
Safari browser on Mac is not supported out of the box in Galen

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#219]

**Comment by hypery2k** [comment]
what do you mean? For me it's working. You need the safari selenium extension

**Comment by ishubin** [comment]
I mean out-of-the-box in here http://galenframework.com/docs/reference-galen-test-suite-syntax/#Definingalocalbrowser

and in here http://galenframework.com/docs/reference-galen-javascript-api/#createDriver

**Comment by hypery2k** [comment]
but does chrome works out of the box without the chromedriver installed?

**Comment by hypery2k** [comment]
I think we should move this to version 1.7, because it's maybe a bigger discussion

**Comment by sachinkodagali** [comment]
Is this issue fixed? I have a safari selenium extension, but when i run the galen test for a JS file i get the following error (Safari launcher opened but not the browser)

org.mozilla.javascript.WrappedException: Wrapped org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10062 ms
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'AutomationMacs-Mac-Pro.local', ip: '10.207.203.106', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_20'
Driver info: driver.version: SafariDriver (<cmd>#37)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.mozilla.javascript.gen._cmd__18._c_createDriver_2(<cmd>:37)
	at org.mozilla.javascript.gen._cmd__18.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._Users_automationmac_Downloads_galen_bin_1_6_4_login_test_js_20._c_anonymous_1(/Users/automationmac/Downloads/galen-bin-1.6.4/login.test.js:4)
	at org.mozilla.javascript.gen._Users_automationmac_Downloads_galen_bin_1_6_4_login_test_js_20.call(/Users/automationmac/Downloads/galen-bin-1.6.4/login.test.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2429)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen._cmd__17._c_invokeFunc_2(<cmd>:31)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._cmd__17._c_anonymous_22(<cmd>:283)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:606)
	at org.mozilla.javascript.JavaAdapter.access$000(JavaAdapter.java:15)
	at org.mozilla.javascript.JavaAdapter$1.run(JavaAdapter.java:586)
	at org.mozilla.javascript.Context.call(Context.java:489)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
	at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:583)
	at adapter1.execute(<adapter>)
	at net.mindengine.galen.TestRunnable.runTest(TestRunnable.java:68)
	at net.mindengine.galen.TestRunnable.run(TestRunnable.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Failed to connect to SafariDriver after 10062 ms

**Comment by hypery2k** [comment]
Which version of the Safari Selenium Extension are you using?
What do you mean with Safari Launcher?

**Comment by sachinkodagali** [comment]
Version is 2.45.0
Snapshot attached for safari launcher which opens after the error mentioned above appears
![screen shot 2015-08-04 at 11 16 34 am](https://cloud.githubusercontent.com/assets/5982311/9054004/51764de8-3a9a-11e5-94b6-88f3d5285281.png)

**Comment by sachinkodagali** [comment]
Any update on the above as we need to run layout tests on Mac safari ..

**Comment by hypery2k** [comment]
with the latest Galen version 2.0.6 it's working for me so safari with 8.0.7 at OS X 10.10

**Comment by sachinkodagali** [comment]
We installed galen latest version 2.1.0. Still issue is present (Safari 8.0.8). Error details below -
AutomationMacs-Mac-Pro:galen-bin-2.0.10 automationmac$ galen test login.test.js --htmlreport .
========================================
Test: Login page test
========================================
Sep 10, 2015 6:08:59 PM org.openqa.selenium.safari.SafariDriverServer start
INFO: Server started on port 9201
Sep 10, 2015 6:08:59 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Launching Safari
Sep 10, 2015 6:08:59 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Waiting for SafariDriver to connect
Sep 10, 2015 6:09:00 PM org.openqa.selenium.safari.SafariDriverChannelHandler$1 operationComplete
INFO: Connection opened
Sep 10, 2015 6:09:00 PM org.openqa.selenium.safari.SafariDriverCommandExecutor start
INFO: Driver connected in 1331 ms
Sep 10, 2015 6:09:00 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutting down
Sep 10, 2015 6:09:00 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Closing connection
Sep 10, 2015 6:09:00 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping Safari
Sep 10, 2015 6:09:00 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Stopping server
Sep 10, 2015 6:09:00 PM org.openqa.selenium.safari.SafariDriverServer stop
INFO: Stopping server
Sep 10, 2015 6:09:00 PM org.openqa.selenium.safari.SafariDriverCommandExecutor stop
INFO: Shutdown complete
org.mozilla.javascript.WrappedException: Wrapped org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'AutomationMacs-Mac-Pro.local', ip: '10.207.8.90', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_20'
Driver info: driver.version: SafariDriver (<cmd>#37)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.mozilla.javascript.gen._cmd__18._c_createDriver_2(<cmd>:37)
	at org.mozilla.javascript.gen._cmd__18.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._Users_automationmac_Downloads_galen_bin_2_0_10_login_test_js_20._c_anonymous_1(/Users/automationmac/Downloads/galen-bin-2.0.10/login.test.js:4)
	at org.mozilla.javascript.gen._Users_automationmac_Downloads_galen_bin_2_0_10_login_test_js_20.call(/Users/automationmac/Downloads/galen-bin-2.0.10/login.test.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2429)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen._cmd__17._c_invokeFunc_2(<cmd>:31)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._cmd__17._c_anonymous_22(<cmd>:283)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:606)
	at org.mozilla.javascript.JavaAdapter.access$000(JavaAdapter.java:15)
	at org.mozilla.javascript.JavaAdapter$1.run(JavaAdapter.java:586)
	at org.mozilla.javascript.Context.call(Context.java:489)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
	at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:583)
	at adapter1.execute(<adapter>)
	at net.mindengine.galen.TestRunnable.runTest(TestRunnable.java:68)
	at net.mindengine.galen.TestRunnable.run(TestRunnable.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'AutomationMacs-Mac-Pro.local', ip: '10.207.8.90', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_20'
Driver info: driver.version: SafariDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:141)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:58)
	at org.openqa.selenium.safari.SafariDriver.<init>(SafariDriver.java:42)
	at net.mindengine.galen.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:96)
	at net.mindengine.galen.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:59)
	at net.mindengine.galen.utils.GalenUtils.createDriver(GalenUtils.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 31 more
Caused by: java.lang.ClassCastException: com.google.gson.JsonObject cannot be cast to java.lang.String
	at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:111)
	at org.openqa.selenium.remote.JsonToBeanConverter.convert(JsonToBeanConverter.java:42)
	at org.openqa.selenium.safari.SafariDriverCommandExecutor.execute(SafariDriverCommandExecutor.java:191)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:578)
	... 44 more

**Comment by hypery2k** [comment]
seems like an Selenium Bug: https://github.com/SeleniumHQ/selenium/issues/631

You can try to update to new safari driver: http://selenium-release.storage.googleapis.com/index.html?path=2.45/
