### ISSUE TITLE
Testing with android and saucelabs fails

### ISSUE THREAD

**Issue by mrlove** [galenframework/galen#232]
I don't know whats going wrong here, but its very difficult to get android and sauce up and running.
Maybe you can give me some feedback.

Spec file:
=====
@@ set
    sauceKey        abcdefgh
    sauceUser       joe
    gridLogin       ${sauceUser}:${sauceKey}
    gridUrl         http://${gridLogin}@ondemand.saucelabs.com:80/wd/hub
    webpage         http://localhost:8181/
    specfile        ../specs/sauce.spec

@@ parameterized
    | browserName   | deviceType | gridArgs                                                       |
    | Android 4.4  | tablet      | --browser android --dc.platform "Linux" --dc.version "4.4" --dc.deviceName "Google Nexus 7C Emulator"      |

Shop Front Page on ${browserName} ${deviceName}
    selenium grid ${gridUrl} --page ${webpage} ${gridArgs}
        check ${specfile} --include ${deviceType}
====

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression node.layoutReport.screenshot is undefined on line 35, column 67 in report-main.
	at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
	at freemarker.core.Expression.getStringValue(Expression.java:118)
	at freemarker.core.Expression.getStringValue(Expression.java:93)
	at freemarker.core.StringBuiltins$StringBuiltIn._getAsTemplateModel(StringBuiltins.java:71)
	at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
	at freemarker.core.Expression.getStringValue(Expression.java:93)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IfBlock.accept(IfBlock.java:82)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Macro$Context.runMacro(Macro.java:172)
	at freemarker.core.Environment.visit(Environment.java:614)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
	at freemarker.core.Environment.visit(Environment.java:428)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IfBlock.accept(IfBlock.java:82)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Macro$Context.runMacro(Macro.java:172)
	at freemarker.core.Environment.visit(Environment.java:614)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
	at freemarker.core.Environment.visit(Environment.java:428)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IfBlock.accept(IfBlock.java:82)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Macro$Context.runMacro(Macro.java:172)
	at freemarker.core.Environment.visit(Environment.java:614)
	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
	at freemarker.core.Environment.visit(Environment.java:428)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.MixedContent.accept(MixedContent.java:92)
	at freemarker.core.Environment.visit(Environment.java:221)
	at freemarker.core.Environment.process(Environment.java:199)
	at freemarker.template.Template.process(Template.java:259)
	at net.mindengine.galen.reports.HtmlReportBuilder.exportTestReport(HtmlReportBuilder.java:82)
	at net.mindengine.galen.reports.HtmlReportBuilder.build(HtmlReportBuilder.java:62)
	at net.mindengine.galen.GalenMain.createHtmlReport(GalenMain.java:358)
	at net.mindengine.galen.GalenMain.createAllReports(GalenMain.java:352)
	at net.mindengine.galen.GalenMain.runTestsInThreads(GalenMain.java:306)
	at net.mindengine.galen.GalenMain.runTests(GalenMain.java:279)
	at net.mindengine.galen.GalenMain.runTestFiles(GalenMain.java:269)
	at net.mindengine.galen.GalenMain.runTests(GalenMain.java:248)
	at net.mindengine.galen.GalenMain.execute(GalenMain.java:79)
	at net.mindengine.galen.GalenMain.main(GalenMain.java:222)

[main] ERROR net.mindengine.galen.reports.HtmlReportBuilder - Unkown report export

Expression node.layoutReport.screenshot is undefined on line 35, column 67 in report-main.
The problematic instruction:
----------
==> ${node.layoutReport.screenshot?html} [on line 35, column 65 in report-main]
 in user-directive report_node [on line 30, column 25 in report-main]
 in user-directive report_node [on line 30, column 25 in report-main]
 in user-directive report_node [on line 120, column 17 in report-main]

**Comment by ishubin** [comment]
What happens is that it fails to create a screenshot and that resolves as an error when rendering an html report. This particular problem is already fixed in version 1.6 which is going to be released soon.
But why it fails to create a screenshot - I don't know. It could be an issue on the sauce labs side. Do you see any exceptions during screenshot creation in the console output?

**Comment by mrlove** [comment]
Okay, thanks for your fast support. I see only this error message over and over again nothing special...
I think when the remote browser hangs or fails to load the page and the shown error page can not be screenshot by selenium...

**Comment by ishubin** [comment]
Ok, cool! Just wait for the version 1.6 to be released and with it you will get proper reports even if the screenshot is missing
