### ISSUE TITLE
Null pointer exceptions when using % for warnings

### ISSUE THREAD

**Issue by kchuykov** [galenframework/galen#245]
here is my script:
https://www.dropbox.com/s/0kmy4mvqeq0ve8x/bad_galen-accelerator-wellsfargo.zip?dl=0

I am getting this error: 
java.lang.NullPointerException
	at net.mindengine.galen.validation.PageValidation.check(PageValidation.java:64)
	at net.mindengine.galen.validation.SectionValidation.checkObject(SectionValidation.java:282)
	at net.mindengine.galen.validation.SectionValidation.checkObjects(SectionValidation.java:100)
	at net.mindengine.galen.validation.SectionValidation.checkSection(SectionValidation.java:147)
	at net.mindengine.galen.validation.SectionValidation.checkTaggedSection(SectionValidation.java:66)
	at net.mindengine.galen.validation.SectionValidation.check(SectionValidation.java:58)
	at net.mindengine.galen.api.Galen.checkLayoutForPage(Galen.java:115)
	at net.mindengine.galen.api.Galen.checkLayout(Galen.java:81)
	at net.mindengine.galen.api.Galen.checkLayout(Galen.java:65)
	at net.mindengine.galen.api.Galen.checkLayout(Galen.java:51)
	at net.mindengine.galen.suite.actions.GalenPageActionCheck.execute(GalenPageActionCheck.java:46)
	at net.mindengine.galen.runner.GalenPageRunner.executeAction(GalenPageRunner.java:77)
	at net.mindengine.galen.runner.GalenPageRunner.run(GalenPageRunner.java:69)
	at net.mindengine.galen.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:71)
	at net.mindengine.galen.tests.GalenBasicTest.execute(GalenBasicTest.java:53)
	at net.mindengine.galen.TestRunnable.runTest(TestRunnable.java:68)
	at net.mindengine.galen.TestRunnable.run(TestRunnable.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ishubin** [comment]
Thanks a lot for samples. I am going to debug it.

**Comment by ishubin** [comment]
The fix for this bug is in master already

**Comment by ishubin** [comment]
The fix is now released in version 1.6.2
