### ISSUE TITLE
Safari Does not always work with galen.

### ISSUE THREAD

**Issue by kchuykov** [galenframework/galen#246]
About 30% chance that safari will not work.  it does not navigate to the url and I get an error 

TimeoutException: Timed out awaiting response to command "setWindowSize" after 30001 ms (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 30.01 seconds Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: 'Mac-Admin.local', ip: '192.168.80.133', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_05' Driver info: org.openqa.selenium.safari.SafariDriver Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=7.1.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}] Session ID: null
org.openqa.selenium.TimeoutException: Timed out awaiting response to command "setWindowSize" after 30001 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.01 seconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Mac-Admin.local', ip: '192.168.80.133', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.8.0_05'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=7.1.3, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.setSize(RemoteWebDriver.java:801)
	at net.mindengine.galen.browser.SeleniumBrowser.changeWindowSize(SeleniumBrowser.java:50)
	at net.mindengine.galen.runner.GalenPageRunner.run(GalenPageRunner.java:58)
	at net.mindengine.galen.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:71)
	at net.mindengine.galen.tests.GalenBasicTest.execute(GalenBasicTest.java:53)
	at net.mindengine.galen.TestRunnable.runTest(TestRunnable.java:68)
	at net.mindengine.galen.TestRunnable.run(TestRunnable.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hypery2k** [comment]
which WebDriver Safari Extension are you using?

You should align the version with Selenium. So when using Galen 1.5.4 or higher you must use 2.45.0
of the Extension: http://selenium-release.storage.googleapis.com/index.html?path=2.45/
![safariext](https://cloud.githubusercontent.com/assets/979121/6885962/c67b84e0-d62d-11e4-9186-1c137f706f8a.png)

**Comment by hypery2k** [comment]
so fare my Galen Tests are working in Safari. But I'll take a look at the issue

**Comment by hypery2k** [comment]
the problem seems to be caused when running multiple Safari tests within the same local machine

**Comment by kchuykov** [comment]
I verified my extension, and yes, I am running multiple tests

**Comment by hypery2k** [comment]
and which version are you using? How do you run you're tests? Via Java (TestNG, JUnit) or via JavaScript?

**Comment by kchuykov** [comment]
I run with test suit file.

**Comment by hypery2k** [comment]
I'm able to reproduce the issue. I will try to investigate more

**Comment by hypery2k** [comment]
see #268

**Comment by egrigolon** [comment]
Hi @hypery2k, I still have this issue running macOS Sierra 10.12.5 and Safari 10.1.1 (12603.2.4).

`Jun 19, 2017 4:08:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
org.openqa.selenium.NoSuchWindowException: A request to use a window could not be satisfied because the window could not be found. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 33 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'vnteugr.local', ip: '172.20.11.27', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.5', java.version: '1.8.0_112'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=12603.2.4, cleanSession=true, platform=MAC, nativeEvents=true, locationContextEnabled=false, webStorageEnabled=true, browserName=safari, javascriptEnabled=true, platformName=macOS, cssSelectorsEnabled=true}]
Session ID: 298041D1-FAAB-4CF3-AFDE-BFDF869A71AB
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:671)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.setSize(RemoteWebDriver.java:890)
	at com.galenframework.utils.GalenUtils.resizeDriver(GalenUtils.java:308)
	at com.galenframework.browser.SeleniumBrowser.changeWindowSize(SeleniumBrowser.java:55)
	at com.galenframework.runner.GalenPageRunner.run(GalenPageRunner.java:65)
	at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:76)
	at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Any ideas?
