### ISSUE TITLE
Issues with different browser within a Selenium Grid

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#251]
We're experiencing some issues within a Grid-Setup when using [full screenshots](http://galenframework.com/docs/getting-started-configuration/) within different browsers
* Chrome works fine
* IE is cropped 
![selection_004](https://cloud.githubusercontent.com/assets/979121/6942014/ad9b93c6-d884-11e4-9951-dafb4df054dd.png)

* Firefox is very flaky (hangs multiple)

```
Caused by: net.mindengine.galen.parser.SyntaxException: Object "usp-description-*" has incorrect locator
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.process(StateObjectDefinition.java:72)
at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.processLine(PageSpecLineProcessor.java:81)
at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:112)
... 21 more
Caused by: java.lang.NullPointerException
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:386)
at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:445)
at org.openqa.selenium.By$ByCssSelector.findElements(By.java:436)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:340)
at net.mindengine.galen.page.selenium.SeleniumPage.driverFindElements(SeleniumPage.java:138)
at net.mindengine.galen.page.selenium.SeleniumPage.getObjectCount(SeleniumPage.java:220)
at net.mindengine.galen.specs.reader.page.PageSpec.updateMultiObject(PageSpec.java:125)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.addMultiObject(StateObjectDefinition.java:129)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.addObjectToSpec(StateObjectDefinition.java:115)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.process(StateObjectDefinition.java:66)
... 23 more

```

I'm not sure if this relates to the screenshots. I'll try to some test cases within the next days

**Comment by kchuykov** [comment]
I had similar issues with IE, I used different IEdriver to solves this. 2.30.1 seems to work
