### ISSUE TITLE
WebDriver Errors should not be handled as FileSyntaxExceptions

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#253]
NullPointers within the Element locations are leading to a FileSyntaxException:
```
...
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: net.mindengine.galen.parser.FileSyntaxException: Object "usp-description-*" has incorrect locator
in /galen/rwd/footer/definition/footer.spec:5
at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:118)
at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:92)
at net.mindengine.galen.specs.reader.page.PageSpecReader.importPageSpec(PageSpecReader.java:262)
at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.importPageSpec(PageSpecLineProcessor.java:227)
at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.importFile(PageSpecLineProcessor.java:218)
at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.doSpecialInstruction(PageSpecLineProcessor.java:98)
at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.processLine(PageSpecLineProcessor.java:64)
at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:112)
... 21 more
Caused by: net.mindengine.galen.parser.SyntaxException: Object "usp-description-*" has incorrect locator
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.process(StateObjectDefinition.java:72)
at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.processLine(PageSpecLineProcessor.java:81)
at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:112)
... 28 more
Caused by: java.lang.NullPointerException
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:386)
at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:445)
at org.openqa.selenium.By$ByCssSelector.findElements(By.java:436)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:340)
at net.mindengine.galen.page.selenium.SeleniumPage.driverFindElements(SeleniumPage.java:138)
at net.mindengine.galen.page.selenium.SeleniumPage.getObjectCount(SeleniumPage.java:220)
at net.mindengine.galen.specs.reader.page.PageSpec.updateMultiObject(PageSpec.java:125)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.addMultiObject(StateObjectDefinition.java:129)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.addObjectToSpec(StateObjectDefinition.java:115)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.process(StateObjectDefinition.java:66)

```

The same behaviour with WebDriverExceptions:
```
...

at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: net.mindengine.galen.parser.SyntaxException: Object "headline-*" has incorrect locator
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.process(StateObjectDefinition.java:72)
at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.processLine(PageSpecLineProcessor.java:81)
at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:112)
... 21 more
Caused by: org.openqa.selenium.WebDriverException: Session [666bda16-d669-40b6-8aaa-1402059b2ce1] was terminated due to SO_TIMEOUT
Command duration or timeout: 3 milliseconds
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'jenkins-dev-163968', ip: '10.184.84.43', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-504.8.1.el6.x86_64', java.version: '1.8.0_20'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=31.4.0, platform=WINDOWS, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=666bda16-d669-40b6-8aaa-1402059b2ce1, locationContextEnabled=true, webStorageEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 666bda16-d669-40b6-8aaa-1402059b2ce1
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:377)
at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:445)
at org.openqa.selenium.By$ByCssSelector.findElements(By.java:436)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:340)
at net.mindengine.galen.page.selenium.SeleniumPage.driverFindElements(SeleniumPage.java:138)
at net.mindengine.galen.page.selenium.SeleniumPage.getObjectCount(SeleniumPage.java:220)
at net.mindengine.galen.specs.reader.page.PageSpec.updateMultiObject(PageSpec.java:125)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.addMultiObject(StateObjectDefinition.java:129)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.addObjectToSpec(StateObjectDefinition.java:115)
at net.mindengine.galen.specs.reader.page.StateObjectDefinition.process(StateObjectDefinition.java:66)
... 23 more
Caused by: org.openqa.selenium.WebDriverException: Session [666bda16-d669-40b6-8aaa-1402059b2ce1] was terminated due to SO_TIMEOUT
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'jenkins-dev-163968', ip: '10.184.84.43', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-504.8.1.el6.x86_64', java.version: '1.8.0_20'
Driver info: driver.version: unknown
at org.openqa.grid.internal.ActiveTestSessions.getExistingSession(ActiveTestSessions.java:105)
at org.openqa.grid.internal.Registry.getExistingSession(Registry.java:423)
at org.openqa.grid.web.servlet.handler.RequestHandler.getSession(RequestHandler.java:238)
at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:119)
at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:83)
at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:67)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
at org.seleniumhq.jetty7.servlet.ServletHolder.handle(ServletHolder.java:565)
at org.seleniumhq.jetty7.servlet.ServletHandler.doHandle(ServletHandler.java:479)
at org.seleniumhq.jetty7.server.session.SessionHandler.doHandle(SessionHandler.java:225)
at org.seleniumhq.jetty7.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
at org.seleniumhq.jetty7.servlet.ServletHandler.doScope(ServletHandler.java:406)
at org.seleniumhq.jetty7.server.session.SessionHandler.doScope(SessionHandler.java:186)
at org.seleniumhq.jetty7.server.handler.ContextHandler.doScope(ContextHandler.java:965)
at org.seleniumhq.jetty7.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
at org.seleniumhq.jetty7.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
at org.seleniumhq.jetty7.server.Server.handle(Server.java:349)
at org.seleniumhq.jetty7.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
at org.seleniumhq.jetty7.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:47)
at org.seleniumhq.jetty7.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
at org.seleniumhq.jetty7.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
at org.seleniumhq.jetty7.http.HttpParser.parseNext(HttpParser.java:857)
at org.seleniumhq.jetty7.http.HttpParser.parseAvailable(HttpParser.java:235)
at org.seleniumhq.jetty7.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:66)
at org.seleniumhq.jetty7.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:254)
at org.seleniumhq.jetty7.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
at org.seleniumhq.jetty7.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
at java.lang.Thread.run(Thread.java:724)
```

WebDriverExceptions should be simply be rethrown.

**Comment by hypery2k** [comment]
this need also be fixed in Version 2 branch, but I think we should maybe improve the error handling in Release 2 branch. Maybe using an own wrapped exception would be helpfull

**Comment by ishubin** [comment]
But what is the reason for NullPointerException from findElement?

**Comment by hypery2k** [comment]
some AJAX reload action. So the element is then not available anymore

We have a retry handler which catches WebDriverExceptions.

**Comment by ishubin** [comment]
Wow, weird. Have never seen such case

**Comment by hypery2k** [comment]
welcome to Selenium :dancer:
