### ISSUE TITLE
Page Dump generates ranges with exponential format for float values

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#258]
Such thing later resolves in the SyntaxException in page spec reader.
```
Exception in thread "main" net.mindengine.galen.parser.FileSyntaxException: Expecting "px", "to" or "%", got "e+"
    in C:/Users/IBM_ADMIN/Desktop/galenframework/galen-sample-java-tests-master/specs/output.spec:15
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:118)
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:92)
    at net.mindengine.galen.api.Galen.checkLayout(Galen.java:62)
    at net.mindengine.galen.api.Galen.checkLayout(Galen.java:51)
    at net.mindengine.galen.api.Galen.checkLayout(Galen.java:165)
    at net.mindengine.galen.java.sample.tests.ECM_Usability_Desktop.main(ECM_Usability_Desktop.java:176)
Caused by: net.mindengine.galen.parser.SyntaxException: Expecting "px", "to" or "%", got "e+"
    at net.mindengine.galen.parser.ExpectRange.read(ExpectRange.java:66)
    at net.mindengine.galen.parser.ExpectRange.read(ExpectRange.java:25)
    at net.mindengine.galen.specs.reader.SpecComplexProcessor.processSpec(SpecComplexProcessor.java:40)
    at net.mindengine.galen.specs.reader.SpecReader.readSpecWithParams(SpecReader.java:527)
    at net.mindengine.galen.specs.reader.SpecReader.read(SpecReader.java:517)
    at net.mindengine.galen.specs.reader.page.StateDoingSection.readSpec(StateDoingSection.java:87)
    at net.mindengine.galen.specs.reader.page.StateDoingSection.processSpecForSimpleObject(StateDoingSection.java:167)
    at net.mindengine.galen.specs.reader.page.StateDoingSection.process(StateDoingSection.java:117)
    at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.processLine(PageSpecLineProcessor.java:81)
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:112)
    ... 5 more
```

Source https://groups.google.com/forum/#!topic/galen-framework/M6TWRz49o6A

**Comment by ishubin** [comment]
Fixed in master branch
