### ISSUE TITLE
npm install throws "cannot access parent directories: Permission denied"

### ISSUE THREAD

**Issue by p00j4** [galenframework/galen#275]
Logs:
```
npm http 304 https://registry.npmjs.org/jsonpointer
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/is-property
/usr/local/bin/galen -> /usr/local/lib/node_modules/galenframework-cli/bin/galen

> galenframework-cli@1.6.3 install /usr/local/lib/node_modules/galenframework-cli
> node install.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:811
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:811:23)
    at startup (node.js:58:13)
    at node.js:902:3
npm ERR! galenframework-cli@1.6.3 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the galenframework-cli@1.6.3 install script.
npm ERR! This is most likely a problem with the galenframework-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls galenframework-cli
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "galenframework-cli"
npm ERR! cwd /Users/pooja
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pooja/npm-debug.log
npm ERR! not ok code 0
```

more info from , npm-debug.log

```
5557 info install galenframework-cli@1.6.3
5558 verbose unsafe-perm in lifecycle false
5559 info galenframework-cli@1.6.3 Failed to exec install script
5560 info /usr/local/lib/node_modules/galenframework-cli unbuild
5561 info preuninstall galenframework-cli@1.6.3
5562 info uninstall galenframework-cli@1.6.3
5563 verbose true,/usr/local/lib/node_modules,/usr/local/lib/node_modules unbuild galenframework-cli@1.6.3
5564 verbose /usr/local/bin,[object Object] binRoot
5565 info postuninstall galenframework-cli@1.6.3
5566 error galenframework-cli@1.6.3 install: `node install.js`
5566 error Exit status 8
5567 error Failed at the galenframework-cli@1.6.3 install script.
5567 error This is most likely a problem with the galenframework-cli package,
5567 error not with npm itself.
5567 error Tell the author that this fails on your system:
5567 error     node install.js
5567 error You can get their info via:
5567 error     npm owner ls galenframework-cli
5567 error There is likely additional logging output above.
5568 error System Darwin 13.4.0
5569 error command "node" "/usr/local/bin/npm" "install" "-g" "galenframework-cli"
5570 error cwd /Users/pooja
5571 error node -v v0.10.26
5572 error npm -v 1.4.3
5573 error code ELIFECYCLE
5574 verbose exit [ 1, true ]


```

**Comment by hypery2k** [comment]
You should install it with sudo.

```
sudo npm install -g galenframework-cli
```

Please post such issue on the GitHub project [here](https://github.com/hypery2k/galenframework-cli)

**Comment by p00j4** [comment]
had installed with sudo, still the issue exists, share the supported logs
