### ISSUE TITLE
WebDriver instance is incorrectly provided to JavaScript executor from GalenPageActionRunJavascript

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#285]
This resolves in a problem when trying to use GalenPages and use hover function on page element:

```
EvaluatorException: Java constructor for "org.openqa.selenium.interactions.Actions" with arguments "net.mindengine.galen.browser.WebDriverWrapper" not found. (<cmd>#410)
org.mozilla.javascript.EvaluatorException: Java constructor for "org.openqa.selenium.interactions.Actions" with arguments "net.mindengine.galen.browser.WebDriverWrapper" not found. (<cmd>#410)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:913)
	at org.mozilla.javascript.Context.reportRuntimeError(Context.java:969)
	at org.mozilla.javascript.Context.reportRuntimeError2(Context.java:939)
	at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:161)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2348)
	at org.mozilla.javascript.gen._cmd__36._c_anonymous_43(<cmd>:410)
	at org.mozilla.javascript.gen._cmd__36.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.mozilla.javascript.gen.hover_js_38._c_anonymous_3(hover.js:21)
	at org.mozilla.javascript.gen.hover_js_38.call(hover.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)
	at org.mozilla.javascript.gen.hover_js_38._c_script_0(hover.js:30)
	at org.mozilla.javascript.gen.hover_js_38.call(hover.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
	at org.mozilla.javascript.gen.hover_js_38.call(hover.js)
	at org.mozilla.javascript.gen.hover_js_38.exec(hover.js)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1110)
	at net.mindengine.galen.javascript.GalenJsExecutor.eval(GalenJsExecutor.java:98)
	at net.mindengine.galen.suite.actions.GalenPageActionRunJavascript.execute(GalenPageActionRunJavascript.java:58)
	at net.mindengine.galen.runner.GalenPageRunner.executeAction(GalenPageRunner.java:77)
	at net.mindengine.galen.runner.GalenPageRunner.run(GalenPageRunner.java:69)
	at net.mindengine.galen.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:71)
	at net.mindengine.galen.tests.GalenBasicTest.execute(GalenBasicTest.java:53)
	at net.mindengine.galen.TestRunnable.runTest(TestRunnable.java:68)
	at net.mindengine.galen.TestRunnable.run(TestRunnable.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ishubin** [comment]
Fixed in release-2.0 branch
