### ISSUE TITLE
new branch release 2.0 have problem while checking galen -v

### ISSUE THREAD

**Issue by nishantkumar155** [galenframework/galen#286]
/galen# galen -v
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/mindengine/galen/GalenMain : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: net.mindengine.galen.GalenMain. Program will exit

**Comment by ishubin** [comment]
It's not an issue. The new version 2.0 will require Java 1.7. You are running it on Java 1.6 that is why you get this error

**Comment by nishantkumar155** [comment]
thanks ishubin
