### ISSUE TITLE
Errors running Galen in Internet explorer 

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#290]
An object that can easily be found by css in Chrome nad Firefox cannot be found in IE.

.TEST file
```
@@ set testedPage http://samples.galenframework.com/tutorial1/tutorial1.html
 
@@ parameterized
   | browser |
   | firefox |
   | chrome  |
   | ie      |
@@ parameterized
   |  deviceName  |  tags           |  size       |
   |  Desktop     |  desktop,all    |  1920x1080  |
   |  Mobile      |  mobile,all     |  480x1080   |
CreateAccount page on ${deviceName} device on ${browser}
    selenium ${browser} ${testedPage} ${size}
       check home-page.spec --include "${tags}"
```

.SPEC FILE
```
==================================================
header            id     header
caption           xpath  //div[@id='header']/h1
menu              id     menu
menuCell-*        css    #menu a[href="#"] 
contentPanel      id     content-container
sidePanel         id     side-panel
footer            id     footer       
==================================================
@all 
----------------------
header
   width: 100% of screen/width
   height: 100px
menu
   below: header 0px
   contains: menuCell-*
menuCell-1
   height: 50px
   width: 61px
menuCell-2
   height: 50px
   width: 61px
menuCell-3
   height: 50px
   width: 61px
menuCell-4
   height: 50px
   width: 61px
caption
   inside: header
   text is: Header
contentPanel
   below: menu 0px
   width: 100% of screen/width
footer
   width: 100% of screen/width
@desktop
----------------------
menu
   height: 50px
menuCell-1
   inside: menu 0px top left
menuCell-2
   right of: menuCell-1
menuCell-3
   right of: menuCell-2
menuCell-4
   right of: menuCell-3
   
contentPanel
   contains: sidePanel
   
footer
   below: contentPanel 0px
@mobile
----------------------
menu
   height: 100px
   
menuCell-1
   inside: menu 0px top left
menuCell-2
   right of: menuCell-1
menuCell-3
   below: menuCell-1
menuCell-4
   below: menuCell-2
   
footer
   below: contentPanel 220px
 ```

As a result I get below error in IE tests: 
```
PageSpecReaderException: org.openqa.selenium.WebDriverException: Finding elements with css selector == #menu li areturned an unexpected error (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 415 milliseconds Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: 'vm-ed-przepod', ip: '10.57.4.82', os.name: 'Windows Server 2012', os.arch: 'x86', os.version: '6.2', java.version: '1.8.0_45' Driver info: org.openqa.selenium.ie.InternetExplorerDriver Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=10, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:10844/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}] Session ID: b06bba82-a24b-46ae-b25d-3a9a16e256e8 *** Element info: {Using=css selector, value=#menu li a} in home-page.spec:6
net.mindengine.galen.parser.PageSpecReaderException: org.openqa.selenium.WebDriverException: Finding elements with css selector == #menu li areturned an unexpected error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 415 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'vm-ed-przepod', ip: '10.57.4.82', os.name: 'Windows Server 2012', os.arch: 'x86', os.version: '6.2', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=10, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:10844/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: b06bba82-a24b-46ae-b25d-3a9a16e256e8
*** Element info: {Using=css selector, value=#menu li a}
    in home-page.spec:6
	at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:120)
	at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:91)
	at net.mindengine.galen.api.Galen.checkLayout(Galen.java:62)
	at net.mindengine.galen.api.Galen.checkLayout(Galen.java:51)
	at net.mindengine.galen.suite.actions.GalenPageActionCheck.execute(GalenPageActionCheck.java:46)
	at net.mindengine.galen.runner.GalenPageRunner.executeAction(GalenPageRunner.java:77)
	at net.mindengine.galen.runner.GalenPageRunner.run(GalenPageRunner.java:69)
	at net.mindengine.galen.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:71)
	at net.mindengine.galen.tests.GalenBasicTest.execute(GalenBasicTest.java:53)
	at net.mindengine.galen.TestRunnable.runTest(TestRunnable.java:68)
	at net.mindengine.galen.TestRunnable.run(TestRunnable.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: Finding elements with css selector == #menu li areturned an unexpected error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 415 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'vm-ed-przepod', ip: '10.57.4.82', os.name: 'Windows Server 2012', os.arch: 'x86', os.version: '6.2', java.version: '1.8.0_45'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{browserAttachTimeout=0, enablePersistentHover=true, ie.forceCreateProcessApi=false, pageLoadStrategy=normal, ie.usePerProcessProxy=false, ignoreZoomSetting=false, handlesAlerts=true, version=10, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:10844/, takesScreenshot=true, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=dismiss}]
Session ID: b06bba82-a24b-46ae-b25d-3a9a16e256e8
*** Element info: {Using=css selector, value=#menu li a}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:383)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementsByCssSelector(RemoteWebDriver.java:451)
	at org.openqa.selenium.By$ByCssSelector.findElements(By.java:437)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:346)
	at net.mindengine.galen.page.selenium.SeleniumPage.driverFindElements(SeleniumPage.java:138)
	at net.mindengine.galen.page.selenium.SeleniumPage.getObjectCount(SeleniumPage.java:225)
	at net.mindengine.galen.specs.reader.page.PageSpec.updateMultiObject(PageSpec.java:125)
	at net.mindengine.galen.specs.reader.page.StateObjectDefinition.addMultiObject(StateObjectDefinition.java:132)
	at net.mindengine.galen.specs.reader.page.StateObjectDefinition.addObjectToSpec(StateObjectDefinition.java:118)
	at net.mindengine.galen.specs.reader.page.StateObjectDefinition.process(StateObjectDefinition.java:66)
	at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.processLine(PageSpecLineProcessor.java:81)
	at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:111)
	... 13 more
```
Why IE cannot find an element by css?

**Comment by hypery2k** [comment]
come from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/galen-framework/OmQfO66kBFc/BJLry6FebzMJ

I will try to investigate the issue next week

**Comment by ishubin** [comment]
Thanks!
