### ISSUE TITLE
Range approximation in percentage

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#306]
The range approximation as stated in the documentation suggest also working with percentages:
```
# Range approximation
# ~~~~~~~~~~~~~~~~~~~~~
# Defines the approximation value for ranges when using "~" in galen page specs
# This value means how many pixels or percents should it take constructing a range
# e.g. if we define approximation as 5 then the following spec:
#   height: ~ 50 px
# will actually be replaced by Galen with this:
#   height: 45 to 55px
galen.range.approximation=3
```

But I use '1%' I get an error:

```java
 NumberFormatException: For input string: "1%"
java.lang.NumberFormatException: For input string: "1%"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.galenframework.config.GalenConfig.getRangeApproximation(GalenConfig.java:99)
``

**Comment by ishubin** [comment]
What I meant by that is that it works in cases like this:
```
some-panel:
    width ~ 95 % of other-panel-width
```

It will take +-3% from 95% and will convert that statement to range ```92 to 98%```
