### ISSUE TITLE
RasterFormatException in page dump in case the screenshot is smaller than the element area

### ISSUE THREAD

**Issue by ishubin** [galenframework/galen#309]
It shouldn't throw an exception. Instead it should put black pixels in case the area is not covered by the screenshot

**Comment by anotherthomas** [comment]
It might be easier to crop the subimage if it would extend to outside the image.

**Comment by ishubin** [comment]
@anotherthomas While in cases when it is only few pixels smaller your solution would make sense, but what to do in cases when the element position is completely off the page screenshot? Should we just avoid creating an image file at all for this element?

**Comment by ishubin** [comment]
@anotherthomas On the other side - having an image of that element all in black would not be of any help as well, so I guess we could go for your solution

**Comment by lo1tuma** [comment]
It seems like this problem has returned.

I get the following stack trace with galen `2.2.5`.

```
 java.awt.image.RasterFormatException: negative or zero height
 	at java.awt.image.Raster.<init>(Raster.java:1105)
 	at java.awt.image.WritableRaster.<init>(WritableRaster.java:129)
 	at sun.awt.image.SunWritableRaster.<init>(SunWritableRaster.java:129)
 	at sun.awt.image.ByteComponentRaster.<init>(ByteComponentRaster.java:154)
 	at sun.awt.image.ByteInterleavedRaster.<init>(ByteInterleavedRaster.java:191)
 	at sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1261)
 	at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
 	at com.galenframework.api.GalenPageDump.exportAllScreenshots(GalenPageDump.java:192)
 	at com.galenframework.api.GalenPageDump.dumpPage(GalenPageDump.java:121)
 	at com.galenframework.api.GalenPageDump.dumpPage(GalenPageDump.java:74)
 	at com.galenframework.suite.actions.GalenPageActionDumpPage.execute(GalenPageActionDumpPage.java:53)
 	at com.galenframework.runner.GalenPageRunner.executeAction(GalenPageRunner.java:84)
 	at com.galenframework.runner.GalenPageRunner.run(GalenPageRunner.java:76)
 	at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:76)
 	at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
 	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
 	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 	at java.lang.Thread.run(Thread.java:745)
```

My tests run agains firefox version 46 on Mac OS X 10.11 in a saucelabs VM.

**Comment by lo1tuma** [comment]
The worst thing about this problem is, that galen still exits with exit code 0 and the test result is `success`.

**Comment by ishubin** [comment]
@lo1tuma The behavior is correct. I introduced it on purpose since this is just a page dump and I would prefer to get the rest of the elements  generated instead of failing due to one element. 
But in your case it seems that the element location is returned with zero size. Instead of printing exception I will introduce a check that `width > 0 && height > 0`

**Comment by ishubin** [comment]
@lo1tuma I have pushed a fix to release-2.3 branch. I hope to release it very soon (perhaps this week)

**Comment by lo1tuma** [comment]
@ishubin Thanks for your fast answer.

I think you are right, that the width and/or height for the element I’m checking is `0`. I was using the `body` element, switching to `html` seems to fix this problem for me.

Thanks for addressing this problem in 2.3, I guess we have those exceptions since several weeks or months in our CI pipeline without anyone noticing. I’m looking forward to the release 😃.

**Comment by alisharaju94** [comment]
So how can i fix this by code?
