### ISSUE TITLE
SCREENSHOT_AUTORESIZE throws RunTimeException on Appium Android when taking pageDump

### ISSUE THREAD

**Issue by phystem** [galenframework/galen#313]
Driver - Appium AndroidDriver

  While taking pageDump it's throwing the following exception

     java.lang.RuntimeException: Error making screenshot
	at com.galenframework.browser.SeleniumBrowser.createScreenshot(SeleniumBrowser.java:96)
	at com.galenframework.api.PageDump.exportAllScreenshots(PageDump.java:93)

    Caused by: org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 35 milliseconds
    Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
    System info: host: 'PC227375', ip: '10.251.32.211', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_67'
    Session ID: 500ebe86-5729-42a0-a4bd-53f6565a5493
    Driver info: io.appium.java_client.android.AndroidDriver
    Capabilities [{platform=LINUX, javascriptEnabled=true, appActivity=AJRMainActivity, browserName=Android, networkConnectionEnabled=true, udid=4d00bb1f919e4059, desired={platformVersion=, deviceName=Samsung-Paytm, platformName=Android, appActivity=AJRMainActivity, udid=4d00bb1f919e4059, appPackage=net.one97.paytm}, locationContextEnabled=false, appPackage=net.one97.paytm, platformVersion=, databaseEnabled=false, platformName=Android, deviceName=Samsung-Paytm, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:27)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:504)
	at com.galenframework.utils.GalenUtils.resizeScreenshotIfNeeded(GalenUtils.java:181)
	at com.galenframework.utils.GalenUtils.takeScreenshot(GalenUtils.java:300)
	at com.galenframework.browser.SeleniumBrowser.makeSimpleScreenshot(SeleniumBrowser.java:101)
	at com.galenframework.browser.SeleniumBrowser.createScreenshot(SeleniumBrowser.java:94)
	... 15 more

It's throwing exception when trying to execute the javascript. in `resizeScreenshotIfNeeded` function inside `GalenUtils.java`
  
    Double devicePixelRatio = ((Number)((JavascriptExecutor)driver).executeScript(JS_RETRIEVE_DEVICE_PIXEL_RATIO)).doubleValue();

If `GalenProperty.SCREENSHOT_AUTORESIZE` is set to false the pagedump is working fine but the screenshot is too big

**Comment by ishubin** [comment]
That's really bad. If it is like this then we can't do anything with the screenshot. Galen needs to know what the pixel ratio is so it can process the screenshot properly. I am afraid that the only thing we can do here is just catch the exception and return 1.0
