### ISSUE TITLE
 FileNotFoundException: Can't find file or resource:

### ISSUE THREAD

**Issue by k6Labz** [galenframework/galen#316]
I want to run **Mobile** automated test on Saucelabs & these are my files 

**homepage.spec:**
```
===========================================
Body             xpath  /html/body

Header-li	     xpath  /html/body/div/div[1]/div/ul

State            id     cShipState

Province 	     id     province

Form	         id     frm1

Submit           xpath   //*[@id='frm1']/button/img

Footer_Links     xpath  /html/body/div/div[10]

Footer_Mobile    xpath  /html/body/footer

==========================================

@ Grow
------------------------------------

Body 
    width: 400px

Province
    height: < 100px
    width : 184px
    inside: Form 300px right 

Form
    width : 161px
    height: > 400px

Submit
    width : 584px

Footer_Mobile
    width : 100% of screen/width
    height: 18px
    below : Body 500px


**My.test:**
@@ set 
    sauceKey        blablablaballablablbalbalblablablablablabla
    sauceUser       jabbot
    gridLogin       ${sauceUser}:${sauceKey}
    gridUrl         http://${gridLogin}@ondemand.saucelabs.com:80/wd/hub
    Mobile-Web      http://mobile.com
	
@@ table Mobile browser
    | deviceName     | gridArgs                                                                                           | 
    | Android Phone  | --browser android --dc.platform "Linux" --dc.version "5.0" --dc.deviceName  "Android Emulator"   |
    | iPhone iOS     | --browser iphone --dc.platform "OS X 10.9" --dc.version "7.1" --dc.deviceName  "iPhone Simulator"  | 	
	
@@ parameterized using Mobile browser
Home page on ${deviceName} Mobile
    selenium grid ${gridUrl} --page ${Mobile-Web} ${gridArgs}
        check homepage1.gspec 
```
**But after executing the My.test got the following error**

FileNotFoundException: Can't find file or resource:
java.io.FileNotFoundException: Can't find file or resource: 	
	at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:89)
	at net.mindengine.galen.api.Galen.checkLayout(Galen.java:62)
	at net.mindengine.galen.api.Galen.checkLayout(Galen.java:51)
	at net.mindengine.galen.suite.actions.GalenPageActionCheck.execute(GalenPageActionCheck.java:46)
	at net.mindengine.galen.runner.GalenPageRunner.executeAction(GalenPageRunner.java:77)
	at net.mindengine.galen.runner.GalenPageRunner.run(GalenPageRunner.java:69)
	at net.mindengine.galen.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:71)
	at net.mindengine.galen.tests.GalenBasicTest.execute(GalenBasicTest.java:53)
	at net.mindengine.galen.TestRunnable.runTest(TestRunnable.java:68)
	at net.mindengine.galen.TestRunnable.run(TestRunnable.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by ishubin** [comment]
First of all you have inconsistent file naming. You mentioned that you created file ```homepage.spec```, but in your test suite you are trying to check layout in ```homepage1.gspec```

Another things. It seems that you are trying to run specs for old versions. Right now Galen v 2.0 will not be able to read this spec. You need to update the spec to new syntax
