### ISSUE TITLE
File Syntax Exception in Galen 2.0.10

### ISSUE THREAD

**Issue by sachinkodagali** [galenframework/galen#323]
Hi,

High Priority issue as we have been completely blocked from executing test scripts after installing latest galen

OS = Mac Yosemite
FF = 35, 38, 41

Spec file we are using :

@objects
   buyingInfoTab div[data-tab="buy"]

= Main Section = 
buyingInfoTab:
   width 227 to 232 px
   height 52 to 57 px

We have installed Latest Galen 2.0.10. However we are getting the FileSyntax Exception

Note that we tried both spaces and tabs with the new syntax.

Note : We are using Open VPN to access our websites.

Also error messages we have got is as below 

net.mindengine.galen.parser.FileSyntaxException: There is no object defined in section
   in chimera-homepage.spec:2
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:116)
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:90)
    at net.mindengine.galen.api.Galen.checkLayout(Galen.java:50)
    at net.mindengine.galen.suite.actions.GalenPageActionCheck.execute(GalenPageActionCheck.java:46)
    at net.mindengine.galen.runner.GalenPageRunner.executeAction(GalenPageRunner.java:77)
    at net.mindengine.galen.runner.GalenPageRunner.run(GalenPageRunner.java:69)
    at net.mindengine.galen.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:66)
    at net.mindengine.galen.tests.GalenBasicTest.execute(GalenBasicTest.java:52)
    at net.mindengine.galen.GalenMain$1.run(GalenMain.java:349)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: net.mindengine.galen.parser.SyntaxException: There is no object defined in section
    at net.mindengine.galen.specs.reader.page.StateDoingSection.processSpecForSimpleObject(StateDoingSection.java:108)
    at net.mindengine.galen.specs.reader.page.StateDoingSection.process(StateDoingSection.java:90)
    at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.processLine(PageSpecLineProcessor.java:85)
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:110)
    ... 11 more

Sachin Kodagali [8:51 PM]
check chimera-homepage.spec --url http://chimera-1.qe2.us-east-1.hubzu.com/chimera/ --size 1440x990 --htmlreport . 
net.mindengine.galen.parser.FileSyntaxException: Incorrect indentation. Should not use tabs. Use spaces
   in chimera-homepage.spec:2
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:116)
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:90)
    at net.mindengine.galen.api.Galen.checkLayout(Galen.java:50)
    at net.mindengine.galen.suite.actions.GalenPageActionCheck.execute(GalenPageActionCheck.java:46)
    at net.mindengine.galen.runner.GalenPageRunner.executeAction(GalenPageRunner.java:77)
    at net.mindengine.galen.runner.GalenPageRunner.run(GalenPageRunner.java:69)
    at net.mindengine.galen.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:66)
    at net.mindengine.galen.tests.GalenBasicTest.execute(GalenBasicTest.java:52)
    at net.mindengine.galen.GalenMain$1.run(GalenMain.java:349)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: net.mindengine.galen.parser.SyntaxException: Incorrect indentation. Should not use tabs. Use spaces
    at net.mindengine.galen.specs.reader.page.StateDoingSection.startsWithIndentation(StateDoingSection.java:154)
    at net.mindengine.galen.specs.reader.page.StateDoingSection.process(StateDoingSection.java:85)
    at net.mindengine.galen.specs.reader.page.PageSpecLineProcessor.processLine(PageSpecLineProcessor.java:85)
    at net.mindengine.galen.specs.reader.page.PageSpecReader.read(PageSpecReader.java:110)
    ... 11 more

**Comment by ishubin** [comment]
Hi it would help if you format your specs code. Because it is completely unclear from your comment how your spec file is structured.
Is the the line ```buyingInfoTab div[data-tab="buy"]``` indented below the line ```@objects``` ?
You can also use https://gist.github.com/ to share code

**Comment by sachinkodagali** [comment]
Thanks. I used the link u shared and updated the code - https://gist.github.com/sachinkodagali/e5ca210ef2f8806c0c9a

Let us know if u need more details. We have also tried tabs / multiple spaces as well ..

**Comment by sachinkodagali** [comment]
Any update on this as its a blocker for us ..

**Comment by ishubin** [comment]
@sachinkodagali I will try to look at it later today, once I get more time

**Comment by sachinkodagali** [comment]
Sure .. We will be waiting for your replu @ishubin

**Comment by ishubin** [comment]
Ok, so I just figured out couple of things.
First of all if I look and your exception thoroughly, then I can see that you are not using the version 2. Because in the version 2 there is no ```StateDoingSection``` class at all. So it seems that you are still running galen test with old version.

Now another issue that I noticed in your file. You are not indenting the object and spec declaration below your section. In your file they are on the same level, but that is incorrect. I have fixed your spec file a bit and tried it with the latest galen 2.1.1 version. Here is the fixed content of your spec:

```
@objects
   buyingInfoTab div[data-tab="buy"]

= Main Section =
   buyingInfoTab:
      width 227 to 232 px
      height 52 to 57 px
```

The thing is that galen specs language has changed quite a lot and now it fully depends on indentation

**Comment by sachinkodagali** [comment]
@ishubin - We were using 2.1.0, as i had mentioned earlier we tried w/ and w/o tabs  (using spaces)

Did u test this on MAC, as mentioned we are using Mac Yosemite - terminal with VPN.

Attached is the snapshot of the issue which also shows that we are using galen 2.1.0
<img width="1030" alt="screen shot 2015-09-30 at 6 35 05 pm" src="https://cloud.githubusercontent.com/assets/5982311/10193636/f3225a72-67a1-11e5-8f24-ae172e1b8edc.png">

**Comment by ishubin** [comment]
Could you please check in the same folder this command?

```
galen -v
```

Because still according to your stacktrace it is not version 2.1.0. All the version starting from 2.0 do not have StateDoingSection class

**Comment by ishubin** [comment]
@sachinkodagali By the way, your image DOES NOT show that you are using galen-2.1.0. The fact that you are in the galen-bin-2.1.0 folder doesn't mean that you are executing the ```galen``` script from that folder, because you don't use ```./```. If you have previously installed galen on that machine, then ```galen``` in your command would refer to the old version

**Comment by ishubin** [comment]
So either reinstall galen 2.1.0 and try it again. But only make sure that ```galen -v``` does print you the new version.

Or instead of running this:
```
galen check chimera-homepage.spec --url http://chimera-1.qe2.us-east-1.hubzu.com/chimera/ --size 1440x990 --htmlreport . 
```

Try this
```
./galen check chimera-homepage.spec --url http://chimera-1.qe2.us-east-1.hubzu.com/chimera/ --size 1440x990 --htmlreport . 
```

**Comment by sachinkodagali** [comment]
@ishubin I have 4 versions installed 1.4, 1.6.4, 2.0.7, 2.1.0 all present in the same parent folder.
We go to the specific folder (after unzipping) and start creating spec / running tests. However when i am in galen-bin-2.1.0 and i try the command (galen -v) i get the version 1.4

Should we uninstall previous versions and try .. if so can you mention the steps

**Comment by hypery2k** [comment]
so how did you make galen available as global command? Entered it in the PATH?

**Comment by sachinkodagali** [comment]
No we havent entered it in a path nor made it available as a global command .. Can you please provide reference link or steps to do so

**Comment by ishubin** [comment]
@sachinkodagali If you want to find out where is your galen installed try this command:

```
which galen | xargs ls -lah
```
and tell us the output of that

**Comment by sachinkodagali** [comment]
@ishubin - I get the following output

lrwxr-xr-x  1 root  wheel    16B Apr 17 14:59 /usr/bin/galen -> /opt/galen/galen

**Comment by ishubin** [comment]
That means that you did install it before via install.sh script. Because that's what the script actually does. It puts the galen bin files in /opt/galen folder and creates a symlink to it in /usr/bin folder. If you want to uninstall, then just remove its symlink and remove /opt/galen.  
Or you can just install the latest version on top of older one

**Comment by sachinkodagali** [comment]
Yes @ishubin we hadn't installed, after installation i see correct version with galen -v

Now code works fine .. thanks so much for ur help :)
