### ISSUE TITLE
Unable to parse command line argument

### ISSUE THREAD

**Issue by kagalenitin** [galenframework/galen#326]
- Galen ver: 
Galen Framework
Version: 2.1.0
JavaScript executor: Rhino 1.7 release 5 2015 01 29
- Java ver: java version "1.8.0_45"
- FF ver. 34.0.5
- From command line call the -D to pass a parameter from command line
   galen test tests/login.test.js -Ddomain=yahoo.com --htmlreport reports

I am accessing the ${domain} value per one of your posts (http://galenframework.com/docs/reference-galen-test-suite-syntax/) - 

==========================
load("init.js");
beforeTest(function() {
       var domValue = ${domain};
	console.log(domValue);
	var driver = openDriver(url, "360x640"); //360x640 //1920x1080
	session.put("driver", driver);
});

==========================

I am getting the below error:

=================================

Exception in thread "main" java.lang.RuntimeException: org.mozilla.javascript.EvaluatorException: missing ; before statement (/tests/login.test.js#7)
	at com.galenframework.GalenMain.execute(GalenMain.java:60)
	at com.galenframework.GalenMain.main(GalenMain.java:78)
Caused by: org.mozilla.javascript.EvaluatorException: missing ; before statement (/tests/login.test.js#7)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
	at org.mozilla.javascript.Parser.addError(Parser.java:188)
	at org.mozilla.javascript.Parser.addError(Parser.java:166)
	at org.mozilla.javascript.Parser.reportError(Parser.java:223)
	at org.mozilla.javascript.Parser.reportError(Parser.java:210)
	at org.mozilla.javascript.Parser.reportError(Parser.java:203)
	at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1067)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1044)
	at org.mozilla.javascript.Parser.statement(Parser.java:901)
	at org.mozilla.javascript.Parser.parse(Parser.java:540)
	at org.mozilla.javascript.Parser.parse(Parser.java:502)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2350)
	at org.mozilla.javascript.Context.compileReader(Context.java:1296)
	at org.mozilla.javascript.Context.compileReader(Context.java:1268)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1107)
	at com.galenframework.javascript.GalenJsExecutor.eval(GalenJsExecutor.java:102)
	at com.galenframework.runner.JsTestCollector.execute(JsTestCollector.java:63)
	at com.galenframework.actions.GalenActionTest.runTestFiles(GalenActionTest.java:100)
	at com.galenframework.actions.GalenActionTest.execute(GalenActionTest.java:84)
	at com.galenframework.GalenMain.execute(GalenMain.java:58)
	... 1 more

=================================

What am I doing something wrong in picking up the variable? 

Your help is much appreciated.

**Comment by ishubin** [comment]
You have an error in your javascript. ${} doesn't work in it. If you want to use the system properties then you can do it via ```System.getProperty("somePropertyName")```

**Comment by kagalenitin** [comment]
Thanks for your response.

Yes - I was referring to one of the examples you mentioned in your comments . I know its an old comment. But I wanted the latest example. Also, I don't want to use a system property.  I want to pass and collect the value in js file. 
<img width="1162" alt="screen shot 2015-10-03 at 12 21 40 pm" src="https://cloud.githubusercontent.com/assets/616741/10264726/63ba05ea-69c9-11e5-8838-c7c4c567efc6.png">

**Comment by ishubin** [comment]
By the way I just noticed in my email notifications that you asked the same question on Disqus comments and in galen-framework google group. Please use google group if you need to get an answer. GitHub issues is not the right place for that. 

Now regarding your question. The arguments that start with ```-D```  are handled as system properties, so if you want to pass an argument from command line then you will have to use system properties.

**Comment by kagalenitin** [comment]
https://groups.google.com/forum/#!topic/galen-framework/180XMwdmv9s - Check this and please comment.

**Comment by ishubin** [comment]
@kagalenitin I have replied you in that article
