### ISSUE TITLE
Galen 2.0 (2.1.2) doesnt wait until whole page isnt loaded

### ISSUE THREAD

**Issue by sachinkodagali** [galenframework/galen#335]
Hi,

Currently in 2.0 (Using 2.1.2 version) galen tests are starting as soon as page load happens. In our UI there are some elements which get loaded around 5-10 seconds after the page load
As the galen tests start before that, it is giving the error (Unable to find the element ...)

However in galen 1.6.4 this issue wasn't seen. For the same website on the same network, galen tests used to start after the page and elements were loaded fine

Can you check?

**Comment by ishubin** [comment]
If you have to deal with dynamic content that has to take some time to load, then you will have to wait for it before checking the layout.
There are various ways of doing that depending on what test suites you are using.

In Standard Galen Test Suites http://galenframework.com/docs/reference-galen-test-suite-syntax/#Waitingfordynamiccontent

GalenPages waitForIt function on every page http://galenframework.com/docs/reference-galenpages-javascript-api/#Quickintroduction

I don't know why it was working for you before, maybe it was a pure luck or maybe now something has changed in Selenium library.

**Comment by sachinkodagali** [comment]
Thanks for the answer. I am using a JS file to run my scripts (as we need to open IE Driver). When i add the wait statement it doesnt work

JS file :

test("Chimera Layout Tests", function() {
        System.setProperty("webdriver.ie.driver", "C://Users//Chimera//Downloads//IEDriverServer.exe");
	var driver = createDriver("http://integ.owners.com", "1440x990", "ie");
		wait 2m until visible "css: section#processOverview" "css: nav.navigation" "css: a.sell" "css: a.buy";
			checkLayout(driver, "chimera-homepage_merged_WinIE.spec");
	driver.quit();
});

Error message i get :

C:\Users\Chimera\Downloads\galen-bin-2.1.2>galen test galen-ie.js --htmlreport .
Exception in thread "main" java.lang.RuntimeException: org.mozilla.javascript.EvaluatorException: missing ; before statement (C:\Users\Chimera\Downloads
        at com.galenframework.GalenMain.execute(GalenMain.java:60)
        at com.galenframework.GalenMain.main(GalenMain.java:78)
Caused by: org.mozilla.javascript.EvaluatorException: missing ; before statement (C:\Users\Chimera\Downloads\galen-bin-2.1.2\galen-ie.js#4)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
        at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
        at org.mozilla.javascript.Parser.addError(Parser.java:188)
        at org.mozilla.javascript.Parser.addError(Parser.java:166)
        at org.mozilla.javascript.Parser.reportError(Parser.java:223)
        at org.mozilla.javascript.Parser.reportError(Parser.java:210)
        at org.mozilla.javascript.Parser.reportError(Parser.java:203)
        at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1067)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1044)
        at org.mozilla.javascript.Parser.statement(Parser.java:901)
        at org.mozilla.javascript.Parser.parseFunctionBody(Parser.java:634)
        at org.mozilla.javascript.Parser.function(Parser.java:795)
        at org.mozilla.javascript.Parser.primaryExpr(Parser.java:2773)
        at org.mozilla.javascript.Parser.memberExpr(Parser.java:2418)
        at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2316)
        at org.mozilla.javascript.Parser.mulExpr(Parser.java:2241)
        at org.mozilla.javascript.Parser.addExpr(Parser.java:2225)
        at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2206)
        at org.mozilla.javascript.Parser.relExpr(Parser.java:2181)
        at org.mozilla.javascript.Parser.eqExpr(Parser.java:2153)
        at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2142)
        at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2131)
        at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2120)
        at org.mozilla.javascript.Parser.andExpr(Parser.java:2109)
        at org.mozilla.javascript.Parser.orExpr(Parser.java:2098)
        at org.mozilla.javascript.Parser.condExpr(Parser.java:2062)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2033)
        at org.mozilla.javascript.Parser.argumentList(Parser.java:2385)
        at org.mozilla.javascript.Parser.memberExprTail(Parser.java:2535)
        at org.mozilla.javascript.Parser.memberExpr(Parser.java:2454)
        at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2316)
        at org.mozilla.javascript.Parser.mulExpr(Parser.java:2241)
        at org.mozilla.javascript.Parser.addExpr(Parser.java:2225)
        at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2206)
        at org.mozilla.javascript.Parser.relExpr(Parser.java:2181)
        at org.mozilla.javascript.Parser.eqExpr(Parser.java:2153)
        at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2142)
        at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2131)
        at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2120)
        at org.mozilla.javascript.Parser.andExpr(Parser.java:2109)
        at org.mozilla.javascript.Parser.orExpr(Parser.java:2098)
        at org.mozilla.javascript.Parser.condExpr(Parser.java:2062)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2033)
        at org.mozilla.javascript.Parser.expr(Parser.java:2012)
        at org.mozilla.javascript.Parser.nameOrLabel(Parser.java:1765)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1032)
        at org.mozilla.javascript.Parser.statement(Parser.java:901)
        at org.mozilla.javascript.Parser.parse(Parser.java:540)
        at org.mozilla.javascript.Parser.parse(Parser.java:502)
        at org.mozilla.javascript.Context.compileImpl(Context.java:2350)
        at org.mozilla.javascript.Context.compileReader(Context.java:1296)
        at org.mozilla.javascript.Context.compileReader(Context.java:1268)
        at org.mozilla.javascript.Context.evaluateReader(Context.java:1107)
        at com.galenframework.javascript.GalenJsExecutor.eval(GalenJsExecutor.java:102)
        at com.galenframework.runner.JsTestCollector.execute(JsTestCollector.java:63)
        at com.galenframework.actions.GalenActionTest.runTestFiles(GalenActionTest.java:100)
        at com.galenframework.actions.GalenActionTest.execute(GalenActionTest.java:84)
        at com.galenframework.GalenMain.execute(GalenMain.java:58)
        ... 1 more

**Comment by ishubin** [comment]
That is because you are mixing two different languages. In my previous comment I gave you two examples for two different things: standard test suites and javascript tests. You just picked the wrong example
