### ISSUE TITLE
Sporadic Screenshot failures in Chrome

### ISSUE THREAD

**Issue by verybadsushi** [galenframework/galen#360]
When running in parallel in Chrome, sometimes the browser fails to take a screenshot.
Should probably wrap the screenshot call in a try catch and retry. Chrome probably has a problem with concurrent screenshots.

Refer to:
http://stackoverflow.com/questions/30224734/sporadic-test-failures-due-to-unknown-error-while-taking-screenshot-in-chromedri

Error Log:
Dec 08, 2015 2:49:45 PM com.galenframework.api.Galen checkLayoutForPage
SEVERE: Error during setting screenshot.
java.lang.RuntimeException: Error making screenshot
	at com.galenframework.browser.SeleniumBrowser.createScreenshot(SeleniumBrowser.java:96)
	at com.galenframework.page.selenium.SeleniumPage.createScreenshot(SeleniumPage.java:171)
	at com.galenframework.api.Galen.checkLayoutForPage(Galen.java:97)
	at com.galenframework.api.Galen.checkLayout(Galen.java:83)
	at com.galenframework.api.Galen.checkLayout(Galen.java:67)
	at com.galenframework.api.Galen.checkLayout(Galen.java:58)
	at com.galenframework.api.Galen.checkLayout(Galen.java:138)
	at com.akqa.automation.common.framework.Galen.checkLayout(Galen.java:48)
	at com.akqa.automation.akqa.selenium.framework.BasePageObject.checkLayout(BasePageObject.java:96)
	at com.akqa.automation.akqa.selenium.framework.BasePageObject.thenIShouldSeeThatThereAreNoLayoutErrorsInSmall(BasePageObject.java:63)
	at com.akqa.automation.akqa.selenium.pageObjects.HomePage.thenIShouldSeeThatThereAreNoLayoutErrorsInSmall(HomePage.java:125)
	at com.akqa.automation.akqa.selenium.tests.HomePageTest.shouldLookGoodOnDesktop(HomePageTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: unknown error: cannot take screenshot
from unknown error: Failed to capture tab: unknown error
JavaScript stack:
Error: Failed to capture tab: unknown error
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:37:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:72:7)
  (Session info: chrome=47.0.2526.73)
  (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.9.4 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 75 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'POM7TFFD57L.local', ip: '10.12.100.40', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.4', java.version: '1.7.0_55'
Session ID: eeb6e9038b731f237e71dbfbe8072d10
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/bh/gnnhbj016yqc6_h2bfl0kv75f1ypp1/T/.org.chromium.Chromium.EuEcow}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=47.0.2526.73, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:325)
	at com.galenframework.utils.GalenUtils.takeScreenshot(GalenUtils.java:294)
	at com.galenframework.browser.SeleniumBrowser.makeSimpleScreenshot(SeleniumBrowser.java:101)
	at com.galenframework.browser.SeleniumBrowser.createScreenshot(SeleniumBrowser.java:94)
	... 26 more

**Comment by ishubin** [comment]
You should be able to make screenshots yourself and then pass it to the checkLayout function. 

In JavaScript API there is a screenshot property - http://galenframework.com/docs/reference-galen-javascript-api/#checkLayout
In Java API check this method http://jdoc.galenframework.com/com/galenframework/api/Galen.html#checkLayout(org.openqa.selenium.WebDriver,%20java.lang.String,%20com.galenframework.speclang2.pagespec.SectionFilter,%20java.util.Properties,%20java.util.Map,%20java.io.File,%20com.galenframework.validation.ValidationListener)
