### ISSUE TITLE
can't install via NPM or manually

### ISSUE THREAD

**Issue by pixelass** [galenframework/galen#375]
I cannot install this

via `npm` I get the following error:

```
08:38 $ sudo npm install -g galenframework-cli
 
> chromedriver@2.20.0 install /usr/local/lib/node_modules/galenframework-cli/node_modules/chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.20/chromedriver_mac32.zip
Saving to /usr/local/lib/node_modules/galenframework-cli/node_modules/chromedriver/chromedriver/chromedriver_mac32.zip
Receiving...
Received 785K...
Received 1573K...
Received 2364K...
Received 3149K...
Received 3434K total.
Extracting zip contents
Copying to target path /usr/local/lib/node_modules/galenframework-cli/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /usr/local/lib/node_modules/galenframework-cli/node_modules/chromedriver/lib/chromedriver/chromedriver
npm WARN cannot run in wd galenframework@2.2.1 node install.js (wd=/usr/local/lib/node_modules/galenframework-cli/node_modules/galenframework)
/usr/local/bin/galen -> /usr/local/lib/node_modules/galenframework-cli/bin/galen

> galenframework-cli@2.2.1 install /usr/local/lib/node_modules/galenframework-cli
> node install.js

Galen installation failed { [Error: Command failed: /usr/local/bin/galen --version
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/galenframework/GalenMain : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/bin/galen --version' } Error: Command failed: /usr/local/bin/galen --version
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/galenframework/GalenMain : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "-g" "galenframework-cli"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! galenframework-cli@2.2.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the galenframework-cli@2.2.1 install script 'node install.js'.
npm ERR! This is most likely a problem with the galenframework-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls galenframework-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pixelass/Downloads/galen-bin-2.2.1/npm-debug.log
```

The logfile has over 10k lines so I'm not sure how helpful it would be to include it.

If I try to manually install I get the following message:

```
ln: /usr/bin/galen: Operation not permitted
```

I'll be happy to post more info if requested.

Running OS X 10.11.1  
I tried different node versions (node.js + io.js)

**Comment by hypery2k** [comment]
please post issues for the NPM package here https://github.com/hypery2k/galenframework-cli/issues

Which Java version are you using? You need JAVA 7+ for Galen!

**Comment by pixelass** [comment]
My bad.. continuing in a new issue here: https://github.com/hypery2k/galenframework-cli/issues/24
