### ISSUE TITLE
FileSyntaxException: Unknown statement: left-of

### ISSUE THREAD

**Issue by vredin** [galenframework/galen#378]
Exception throws when trying to use left-of statement.

oleksandr@VirtualBox:~/autoTest1$ galen -v
Galen Framework
Version: 2.2.1
JavaScript executor: Rhino 1.7 release 5 2015 01 29

 @objects
  4         header-logo     #header-logo
  5         header-text     #header h1
  6 
  7 = Header =
  8         header-logo:
  9         left-of header-text 5px

command: check home.gspec --url http://testapp.galenframework.com/ -size 1024x768 -htmlreport reports
output: 
FileSyntaxException: Unknown statement: left-of header-text 5px in home.gspec:9
com.galenframework.parser.FileSyntaxException: Unknown statement: left-of header-text 5px
    in home.gspec:9
	at com.galenframework.speclang2.pagespec.PageSpecReader.read(PageSpecReader.java:77)
	at com.galenframework.speclang2.pagespec.PageSpecReader.read(PageSpecReader.java:47)
	at com.galenframework.api.Galen.checkLayout(Galen.java:68)
	at com.galenframework.api.Galen.checkLayout(Galen.java:59)
	at com.galenframework.suite.actions.GalenPageActionCheck.execute(GalenPageActionCheck.java:53)
	at com.galenframework.runner.GalenPageRunner.executeAction(GalenPageRunner.java:84)
	at com.galenframework.runner.GalenPageRunner.run(GalenPageRunner.java:76)
	at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:76)
	at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.galenframework.parser.SyntaxException: Unknown statement: left-of header-text 5px
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.processSection(PageSectionProcessor.java:80)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.process(PageSectionProcessor.java:66)
	at com.galenframework.speclang2.pagespec.PostProcessor.processNode(PostProcessor.java:39)
	at com.galenframework.speclang2.pagespec.PostProcessor.process(PostProcessor.java:33)
	at com.galenframework.speclang2.pagespec.PageSpecReader.read(PageSpecReader.java:65)

**Comment by ishubin** [comment]
@vredin could you please format the spec code so that indentation is kept to its original? My guess is that this error is caused by indentation

**Comment by ishubin** [comment]
This should be the correct code, please try it and see if it works for you:

```
@objects
    header-logo #header-logo
    header-text #header h1

= Header =
    header-logo:
        left-of header-text 5px
```

**Comment by vredin** [comment]
thanks, that works for me now.

**Comment by anjali23mishra** [comment]
@objects

header  css  div#header
   logo css  img
   text css  h1

menu css  div#menu
   item-* css li


=Header=
 @on desktop
header:
       height ~69px
       centered horizontally inside screen
       
header.logo:
        height 48px
        width 48px
        inside header 13px top,0px left

header.text:
        inside header near header.logo 20 to 30px right
        text is "Sample Website for Galen Framework"
        css font-size is "36px"
        css font-weight is "500"

=Menu=
  @on desktop 
menu:
       below header 0px

**Comment by anjali23mishra** [comment]
@objects

header  css  div#header
   logo css  img
   text css  h1

menu css  div#menu
   item-* css li


=Header=
 @on desktop
header:
       height ~69px
       centered horizontally inside screen
       
header.logo:
        height 48px
        width 48px
        inside header 13px top,0px left

header.text:
        inside header near header.logo 20 to 30px right
        text is "Sample Website for Galen Framework"
        css font-size is "36px"
        css font-weight is "500"

=Menu=
  @on desktop 
menu:
       below header 0px
       

     
                 
Whats wrong with this specs file,i am not able to run my testcase
