### ISSUE TITLE
Galen in a CI environment

### ISSUE THREAD

**Issue by Lightheaded** [galenframework/galen#385]
Hello!

I'would very much like to run Galen in my TeamCity server (or in a Vagrant container for that matter), but as they don't have a screen, tests fail with the error saying there are no displays specified:

```
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

(firefox:2194): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Error: no display specified
```

Is it possible to run Galen in an environment without a display?

**Comment by hypery2k** [comment]
yes you need Xvfb for this, see https://gist.github.com/tommeier/944047

**Comment by Lightheaded** [comment]
Thanks for the tip! I followed the instructions and got it xvfb running. It doesn't complain about screen any more, but it does complain about something else I'm not able to decrypt

```
$ npm test

> web_public@1.0.0 test /vagrant
> cd test/galen-tests/ && galen test suite.test --htmlreport reports -Ddomain=https://fortumo.com

========================================
Test: Homepage on desktop-2 device
========================================
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
vider
1454055443490	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1454055443490	addons.manager	DEBUG	Provider finished startup: PluginProvider
1454055443490	addons.manager	DEBUG	Completed startup sequence
1454055443747	DeferredSave.extensions.json	DEBUG	Save changes
1454055443748	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"_4Gw1PDhVxM5","location":"app-profile","version":"2.47.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":false,"descriptor":"/tmp/anonymous8776609466061168447webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1454055440000,"updateDate":1454055440000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1454055443748	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1454055443753	DeferredSave.extensions.json	DEBUG	Save changes
1454055443757	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"_4Gw1PDhVxM5","location":"app-profile","version":"2.47.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"descriptor":"/tmp/anonymous8776609466061168447webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1454055440000,"updateDate":1454055440000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1454055443851	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1454055443851	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1454055443852	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1454055444181	DeferredSave.extensions.json	DEBUG	Write succeeded
1454055444181	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1454055444181	DeferredSave.extensions.json	DEBUG	Starting timer
1454055444214	DeferredSave.extensions.json	DEBUG	Starting write
1454055444228	addons.repository	DEBUG	No addons.json found.
1454055444230	DeferredSave.addons.json	DEBUG	Save changes
1454055444236	DeferredSave.addons.json	DEBUG	Starting timer
1454055444251	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1454055444255	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1454055444255	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1454055444274	DeferredSave.extensions.json	DEBUG	Write succeeded
1454055444296	DeferredSave.addons.json	DEBUG	Starting write
1454055444330	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:221)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
	at com.galenframework.browser.SeleniumBrowserFactory.getDriver(SeleniumBrowserFactory.java:95)
	at com.galenframework.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:89)
	at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:65)
	at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:73)
	at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows:
vider
1454055443490	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1454055443490	addons.manager	DEBUG	Provider finished startup: PluginProvider
1454055443490	addons.manager	DEBUG	Completed startup sequence
1454055443747	DeferredSave.extensions.json	DEBUG	Save changes
1454055443748	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"_4Gw1PDhVxM5","location":"app-profile","version":"2.47.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":false,"descriptor":"/tmp/anonymous8776609466061168447webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1454055440000,"updateDate":1454055440000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1454055443748	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1454055443753	DeferredSave.extensions.json	DEBUG	Save changes
1454055443757	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"_4Gw1PDhVxM5","location":"app-profile","version":"2.47.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"descriptor":"/tmp/anonymous8776609466061168447webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1454055440000,"updateDate":1454055440000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1454055443851	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1454055443851	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1454055443852	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1454055444181	DeferredSave.extensions.json	DEBUG	Write succeeded
1454055444181	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1454055444181	DeferredSave.extensions.json	DEBUG	Starting timer
1454055444214	DeferredSave.extensions.json	DEBUG	Starting write
1454055444228	addons.repository	DEBUG	No addons.json found.
1454055444230	DeferredSave.addons.json	DEBUG	Save changes
1454055444236	DeferredSave.addons.json	DEBUG	Starting timer
1454055444251	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1454055444255	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1454055444255	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1454055444274	DeferredSave.extensions.json	DEBUG	Write succeeded
1454055444296	DeferredSave.addons.json	DEBUG	Starting write
1454055444330	DeferredSave.addons.json	DEBUG	Write succeeded

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'vagrant-ubuntu-trusty-64', ip: '10.0.2.15', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-76-generic', java.version: '1.7.0_91'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:134)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:221)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:133)
	at com.galenframework.browser.SeleniumBrowserFactory.getDriver(SeleniumBrowserFactory.java:95)
	at com.galenframework.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:89)
	at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:65)
	at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:73)
	at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
vider
1454055443490	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1454055443490	addons.manager	DEBUG	Provider finished startup: PluginProvider
1454055443490	addons.manager	DEBUG	Completed startup sequence
1454055443747	DeferredSave.extensions.json	DEBUG	Save changes
1454055443748	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"_4Gw1PDhVxM5","location":"app-profile","version":"2.47.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":false,"descriptor":"/tmp/anonymous8776609466061168447webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1454055440000,"updateDate":1454055440000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1454055443748	addons.xpi	DEBUG	getModTime: Recursive scan of fxdriver@googlecode.com
1454055443753	DeferredSave.extensions.json	DEBUG	Save changes
1454055443757	addons.xpi	DEBUG	Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"_4Gw1PDhVxM5","location":"app-profile","version":"2.47.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"descriptor":"/tmp/anonymous8776609466061168447webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1454055440000,"updateDate":1454055440000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8234871,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
1454055443851	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1454055443851	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1454055443852	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1454055444181	DeferredSave.extensions.json	DEBUG	Write succeeded
1454055444181	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
1454055444181	DeferredSave.extensions.json	DEBUG	Starting timer
1454055444214	DeferredSave.extensions.json	DEBUG	Starting write
1454055444228	addons.repository	DEBUG	No addons.json found.
1454055444230	DeferredSave.addons.json	DEBUG	Save changes
1454055444236	DeferredSave.addons.json	DEBUG	Starting timer
1454055444251	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1454055444255	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1454055444255	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
1454055444274	DeferredSave.extensions.json	DEBUG	Write succeeded
1454055444296	DeferredSave.addons.json	DEBUG	Starting write
1454055444330	DeferredSave.addons.json	DEBUG	Write succeeded

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:122)
```

**Comment by Lightheaded** [comment]
I think it has something to do with extension signing, but this is hardly related to galen. Thanks for the tip anyway :)

**Comment by ishubin** [comment]
@Lightheaded By the way you can also take a look at PhantomJS browser. If you use it then you don't have to configure Xvfb as far as I remember as it is a GUI-less browser

**Comment by Lightheaded** [comment]
I decided to go for PhantomJS as with using other webdrivers (chrome, firefox) the tests just hanged for a while and in the end reported that no screen is available. I did try the following methods and none of those worked..
https://gist.github.com/curtismcmullan/7be1a8c1c841a9d8db2c
http://christopher.su/2015/selenium-chromedriver-ubuntu/

The drivers themselves worked, but Galen didn't seem to recognize the drivers, although I provided the paths to executables via `-Dwebdriver.chrome.driver=/usr/local/bin/chromedriver` etc.

If you could perhaps find half an hour of your time to create a Vagrantfile for setting up Galen tests with different webdrivers, it would serve as rock-solid documentation AND a working example, which could be directly used for running the tests in CI environments and also make onboarding new develoeprs much easier.

**Comment by ishubin** [comment]
@Lightheaded I don't have time for that to be honest. I have too much stuff on my roadmap already. But Galen has almost nothing to do with this. As Galen is based on Selenium, you could look for any other tutorials on the internet related to Selenium + PhantomJs/Chrome etc.
