### ISSUE TITLE
Heap memory issues

### ISSUE THREAD

**Issue by hypery2k** [galenframework/galen#386]
I'm getting memory issues when using image comparison:
```
java.lang.OutOfMemoryError: Java heap space
        at com.galenframework.rainbow4j.ImageHandler.readRgbModelFrom(ImageHandler.java:53)
        at com.galenframework.rainbow4j.ImageHandler.<init>(ImageHandler.java:30)
        at com.galenframework.rainbow4j.Rainbow4J.compare(Rainbow4J.java:86)
        at com.galenframework.validation.specs.SpecValidationImage.checkImages(SpecValidationImage.java:148)
        at com.galenframework.validation.specs.SpecValidationImage.check(SpecValidationImage.java:94)
        at com.galenframework.validation.specs.SpecValidationImage.check(SpecValidationImage.java:40)
        at com.galenframework.validation.PageValidation.check(PageValidation.java:71)
        at com.galenframework.validation.PageValidation.check(PageValidation.java:61)
        at com.galenframework.validation.SectionValidation.checkObject(SectionValidation.java:165)
        at com.galenframework.validation.SectionValidation.checkSpecGroups(SectionValidation.java:90)
        at com.galenframework.validation.SectionValidation.checkObjects(SectionValidation.java:77)
        at com.galenframework.validation.SectionValidation.checkSection(SectionValidation.java:109)
        at com.galenframework.validation.SectionValidation.checkPageSection(SectionValidation.java:54)
        at com.galenframework.validation.SectionValidation.check(SectionValidation.java:47)
        at com.galenframework.api.Galen.checkLayoutForPage(Galen.java:113)
        at com.galenframework.api.Galen.checkLayout(Galen.java:86)
        at com.galenframework.api.Galen.checkLayout(Galen.java:69)
        at com.galenframework.javascript.GalenJsApi.checkLayout(GalenJsApi.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at org.mozilla.javascript.gen._cmd__18._c_checkLayout_7(<cmd>:135)
        at org.mozilla.javascript.gen._cmd__18.call(<cmd>)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
```
I had to increae HeapSize in galen.bat:
```
@echo off
SET mypath=%~dp0
java -Xmx4096m -cp "%mypath%\galen.jar;lib/*;libs/*" com.galenframework.GalenMain %*
```
Maybe we got an memory issue due to not releasing some resources?

**Comment by hypery2k** [comment]
The PR does not fix the issue complety: 
```java
Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: Java heap space
        at com.galenframework.rainbow4j.ImageHandler.readRgbModelFrom(ImageHandler.java:49)
        at com.galenframework.rainbow4j.ImageHandler.<init>(ImageHandler.java:32)
        at com.galenframework.rainbow4j.Rainbow4J.compare(Rainbow4J.java:87)
        at com.galenframework.validation.specs.SpecValidationImage.checkImages(SpecValidationImage.java:148)
        at com.galenframework.validation.specs.SpecValidationImage.check(SpecValidationImage.java:94)
        at com.galenframework.validation.specs.SpecValidationImage.check(SpecValidationImage.java:40)
        at com.galenframework.validation.PageValidation.check(PageValidation.java:71)
        at com.galenframework.validation.PageValidation.check(PageValidation.java:61)
        at com.galenframework.validation.SectionValidation.checkObject(SectionValidation.java:165)
        at com.galenframework.validation.SectionValidation.checkSpecGroups(SectionValidation.java:90)
        at com.galenframework.validation.SectionValidation.checkObjects(SectionValidation.java:77)
        at com.galenframework.validation.SectionValidation.checkSection(SectionValidation.java:109)
        at com.galenframework.validation.SectionValidation.checkPageSection(SectionValidation.java:54)
        at com.galenframework.validation.SectionValidation.check(SectionValidation.java:47)
        at com.galenframework.api.Galen.checkLayoutForPage(Galen.java:113)
        at com.galenframework.api.Galen.checkLayout(Galen.java:86)
        at com.galenframework.api.Galen.checkLayout(Galen.java:69)
```
