### ISSUE TITLE
Null pointer and File not found exception while running the First Project test on Firefox browser

### ISSUE THREAD

**Issue by PrasadMadge** [galenframework/galen#395]
My gelya1.gspec file =>

@objects
    header              id      header

= Main section =
    header:
        height 40to 120px

Galen command =>
D:\Galen\Project1>galen check gelya1.gspec \ --url http://samples.galenframework
.com/tutorial1/tutorial1.html  \ --size 640x480  \ --htmlreport .

Firefox browser is launching four times and these are the error logs =>

D:\Galen\Project1>galen check gelya1.gspec \ --url http://samples.galenframework
.com/tutorial1/tutorial1.html  \ --size 640x480  \ --htmlreport .
========================================
Test: gelya1.gspec
========================================
check  gelya1.gspec \ --url http://samples.galenframework.com/tutorial1/tutorial
1.html \ --size 640x480 \ --htmlreport .
**java.lang.NullPointerException**
        at com.galenframework.utils.GalenUtils.resizeScreenshotIfNeeded(GalenUti
ls.java:186)
        at com.galenframework.utils.GalenUtils.takeScreenshot(GalenUtils.java:31
6)
        at com.galenframework.browser.SeleniumBrowser.makeSimpleScreenshot(Selen
iumBrowser.java:97)
        at com.galenframework.browser.SeleniumBrowser.createScreenshot(SeleniumB
rowser.java:90)
        at com.galenframework.page.selenium.SeleniumPage.createScreenshot(Seleni
umPage.java:161)
        at com.galenframework.api.Galen.checkLayoutForPage(Galen.java:100)
        at com.galenframework.api.Galen.checkLayout(Galen.java:86)
        at com.galenframework.api.Galen.checkLayout(Galen.java:69)
        at com.galenframework.api.Galen.checkLayout(Galen.java:59)
        at com.galenframework.suite.actions.GalenPageActionCheck.execute(GalenPa
geActionCheck.java:53)
        at com.galenframework.runner.GalenPageRunner.executeAction(GalenPageRunn
er.java:84)
        at com.galenframework.runner.GalenPageRunner.run(GalenPageRunner.java:76
)
        at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTest
Runner.java:76)
        at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:5
5)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
= Main section =
    header:
        height 40to 120px

========================================
Test: \
========================================
check  gelya1.gspec \ --url http://samples.galenframework.com/tutorial1/tutorial
1.html \ --size 640x480 \ --htmlreport .
**java.io.FileNotFoundException: **\ (The system cannot find the path specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.galenframework.utils.GalenUtils.findFileOrResourceAsStream(GalenU
tils.java:365)
        at com.galenframework.speclang2.pagespec.PageSpecReader.read(PageSpecRea
der.java:43)
        at com.galenframework.api.Galen.checkLayout(Galen.java:68)
        at com.galenframework.api.Galen.checkLayout(Galen.java:59)
        at com.galenframework.suite.actions.GalenPageActionCheck.execute(GalenPa
geActionCheck.java:53)
        at com.galenframework.runner.GalenPageRunner.executeAction(GalenPageRunn
er.java:84)
        at com.galenframework.runner.GalenPageRunner.run(GalenPageRunner.java:76
)
        at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTest
Runner.java:76)
        at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:5
5)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
========================================
Test: \
========================================
check  gelya1.gspec \ --url http://samples.galenframework.com/tutorial1/tutorial
1.html \ --size 640x480 \ --htmlreport .
**java.io.FileNotFoundException**: \ (The system cannot find the path specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.galenframework.utils.GalenUtils.findFileOrResourceAsStream(GalenU
tils.java:365)
        at com.galenframework.speclang2.pagespec.PageSpecReader.read(PageSpecRea
der.java:43)
        at com.galenframework.api.Galen.checkLayout(Galen.java:68)
        at com.galenframework.api.Galen.checkLayout(Galen.java:59)
        at com.galenframework.suite.actions.GalenPageActionCheck.execute(GalenPa
geActionCheck.java:53)
        at com.galenframework.runner.GalenPageRunner.executeAction(GalenPageRunn
er.java:84)
        at com.galenframework.runner.GalenPageRunner.run(GalenPageRunner.java:76
)
        at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTest
Runner.java:76)
        at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:5
5)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
========================================
Test: \
========================================
check  gelya1.gspec \ --url http://samples.galenframework.com/tutorial1/tutorial
1.html \ --size 640x480 \ --htmlreport .
**java.io.FileNotFoundException**: \ (The system cannot find the path specified)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.galenframework.utils.GalenUtils.findFileOrResourceAsStream(GalenU
tils.java:365)
        at com.galenframework.speclang2.pagespec.PageSpecReader.read(PageSpecRea
der.java:43)
        at com.galenframework.api.Galen.checkLayout(Galen.java:68)
        at com.galenframework.api.Galen.checkLayout(Galen.java:59)
        at com.galenframework.suite.actions.GalenPageActionCheck.execute(GalenPa
geActionCheck.java:53)
        at com.galenframework.runner.GalenPageRunner.executeAction(GalenPageRunn
er.java:84)
        at com.galenframework.runner.GalenPageRunner.run(GalenPageRunner.java:76
)
        at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTest
Runner.java:76)
        at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:5
5)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

========================================
----------------------------------------
========================================
Failed tests:
    \
    \
    \

Suite status: FAIL
Total tests: 4
Total failed tests: 3
Total failures: 3
There were failures in galen tests

**Comment by ishubin** [comment]
Hi, please remove the backslash `\` in your galen command. I guess you just copied it the way it is on the official documents and put it all in one line.

I don't know how it is in Windows but in Linux the backslash at the end of the line is used for splitting a single command over multiple lines (http://stackoverflow.com/questions/18599711/how-can-i-split-a-bash-command-over-multiple-lines-when-using-an-if-statement)
