### ISSUE TITLE
ERROR com.galenframework.api.Galen - Error during setting screenshot.

### ISSUE THREAD

**Issue by PrasadMadge** [galenframework/galen#398]
I am trying to do galen layout testing on an Android device through appium.
I have tested my appium driver and did some operations and it is working fine.

This is my java class to do Layout testing on android device through appium

`package plus;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import java.util.Properties;

import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

import com.galenframework.api.Galen;
import com.galenframework.reports.GalenTestInfo;
import com.galenframework.reports.HtmlReportBuilder;
import com.galenframework.reports.model.LayoutReport;
import com.galenframework.testng.GalenTestNgTestBase;

public class WelcomePageTest extends GalenTestNgTestBase  {
	private RemoteWebDriver driver;
	
	
	@Override
	public WebDriver createDriver(Object[] args) {
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("platformVersion", "5.0");
		capabilities.setCapability("deviceName", "Android");
		capabilities.setCapability("browserName", "chrome");
		try {
			driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return driver;
	}
	
	@Test
    public void welcomePage_shouldLookGood_onDesktopDevice() throws IOException {
		
		List<String> includedTags = new ArrayList<String>();
		Properties p = new Properties();
		LayoutReport layoutReport=null;
		try{
			layoutReport	=Galen.checkLayout(driver, "specs/gelya1.gspec",Arrays.asList("mobile"));
		}catch(Exception e){
			System.out.println("error :-( "+e);
		}

		// Creating a list of tests
		List<GalenTestInfo> tests = new LinkedList<GalenTestInfo>();

		// Creating an object that will contain the information about the test
		GalenTestInfo test = GalenTestInfo.fromString("Login page on mobile device test");

		// Adding layout report to the test report
		test.getReport().layout(layoutReport, "check layout on mobile device");
		tests.add(test);

		// Exporting all test reports to html
		new HtmlReportBuilder().build(tests, "target/galen-html-reports");
		
		
        /*load("http://google.com", 1024, 768);
        checkLayout("/specs/welcomePage.spec",  Arrays.asList("mobile"));*/
    }
	

}
`

These are the error logs :+1: 

`[main] ERROR com.galenframework.api.Galen - Error during setting screenshot.
java.lang.RuntimeException: Error making screenshot
	at com.galenframework.browser.SeleniumBrowser.createScreenshot(SeleniumBrowser.java:92)
	at com.galenframework.page.selenium.SeleniumPage.createScreenshot(SeleniumPage.java:161)
	at com.galenframework.api.Galen.checkLayoutForPage(Galen.java:100)
	at com.galenframework.api.Galen.checkLayout(Galen.java:86)
	at com.galenframework.api.Galen.checkLayout(Galen.java:69)
	at com.galenframework.api.Galen.checkLayout(Galen.java:59)
	at com.galenframework.api.Galen.checkLayout(Galen.java:154)
	at com.galenframework.api.Galen.checkLayout(Galen.java:128)
	at plus.WelcomePageTest.welcomePage_shouldLookGood_onDesktopDevice(WelcomePageTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException
	at com.galenframework.utils.GalenUtils.takeScreenshot(GalenUtils.java:310)
	at com.galenframework.browser.SeleniumBrowser.makeSimpleScreenshot(SeleniumBrowser.java:97)
	at com.galenframework.browser.SeleniumBrowser.createScreenshot(SeleniumBrowser.java:90)
	... 31 more`

Galen Jar files were imported from the Maven repository mentioned in the examples(2.2.1).

I have tried running layout testing spec files on the android devices through bat files externally(Faidys project) , and they were running fine . The same thing when I tried doing it through galen Api I am getting screen shot error. Please resolve this issue

**Comment by ishubin** [comment]
According to your stacktrace the problem is in this line of code https://github.com/galenframework/galen/blob/galen-2.2.1/galen-core/src/main/java/com/galenframework/utils/GalenUtils.java#L310. The only reason for it to throw a NullPointerException is if your driver was not correctly initialized.

I think this is the part to blame:
```
    try {
        driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
    } catch (MalformedURLException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    return driver;
```

You shouldn't just print the stack trace and proceed. If it fails creating a driver - it should fail the whole test

**Comment by PrasadMadge** [comment]
Hi Ivan , this is completely new issue which I am facing , 


While I am running the internalization layout testing project in mindengine website I am getting a syntax error , I have mentioned a comment there , please help me I want to use internalization in my project. 

Thanking you in advance 
Prasad
