### ISSUE TITLE
CSS selector for first child in Javascript API

### ISSUE THREAD

**Issue by snehatulsi** [galenframework/galen#423]
I am trying to write functional tests using Galen javascript API.

    this.menu = $page("Menu Bar", {
        menuItem: ".section li:first-child div"
    });

It seems css selector first-child is wrong here. 

I can do the same using xpath: `xpath: //*[@class='section']//li[1]//div`

But I want to do using CSS selector. Please help

**Comment by ishubin** [comment]
This is not an issue of galen

**Comment by ishubin** [comment]
Please try to google this question for Selenium

**Comment by snehatulsi** [comment]
Selenium supports nth-child selector. But galen throws error

> org.mozilla.javascript.JavaScriptException: Error: Unknown locator type: .utility-section>div (<cmd>#79)

**Comment by ishubin** [comment]
damn it! I totally missed that. Sorry. Try to change it to this:
```
this.menu = $page("Menu Bar", {
    menuItem: "css: .section li:first-child div"
});
```

**Comment by cyildirim** [comment]
Test Ok. I tested this issue and i now sharing the results. 

At master branch -----
test.js
```
test("Home page", function() {

	var driver = createDriver("http://sahibinden.com","1028x768","chrome");

	CategoryMain = $page("Category", {
		emlakField: ".categories-left-menu li:first-child a",
	  categoryClick: loggedFunction("deneme",function () { this.emlakField.click() })
	});

	var categoryMain = new CategoryMain(driver);
	categoryMain.categoryClick();
	driver.quit();

});

```


```
can@cans-MacBook-Pro-3 ~/galenbug423 $ galen test test.js -Dwebdriver.chrome.driver=/etc/chromedriver               [ruby-2.0.0p648]
========================================
Test: Home page
========================================
Starting ChromeDriver 2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708) on port 40856
Only local connections are allowed.
org.mozilla.javascript.JavaScriptException: Error: Unknown locator type: .categories-left-menu li (<cmd>#79)
	at org.mozilla.javascript.gen._cmd__19._c_anonymous_6(<cmd>:79)
	at org.mozilla.javascript.gen._cmd__19.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen._cmd__19._c_anonymous_22(<cmd>:277)
	at org.mozilla.javascript.gen._cmd__19.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.mozilla.javascript.gen._cmd__19._c_anonymous_19(<cmd>:261)
	at org.mozilla.javascript.gen._cmd__19.call(<cmd>)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:341)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2348)
	at org.mozilla.javascript.gen._cmd__19._c_anonymous_8(<cmd>:98)
	at org.mozilla.javascript.gen._cmd__19.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.mozilla.javascript.gen._cmd__19._c_anonymous_73(<cmd>:656)
	at org.mozilla.javascript.gen._cmd__19.call(<cmd>)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:341)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2348)
	at org.mozilla.javascript.gen._Users_can_galenbug423_test_js_20._c_anonymous_1(/Users/can/galenbug423/test.js:10)
	at org.mozilla.javascript.gen._Users_can_galenbug423_test_js_20.call(/Users/can/galenbug423/test.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2429)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
	at org.mozilla.javascript.gen._cmd__17._c_invokeFunc_2(<cmd>:31)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._cmd__17._c_anonymous_22(<cmd>:280)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:606)
	at org.mozilla.javascript.JavaAdapter.access$000(JavaAdapter.java:15)
	at org.mozilla.javascript.JavaAdapter$1.run(JavaAdapter.java:586)
	at org.mozilla.javascript.Context.call(Context.java:489)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
	at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:583)
	at adapter1.execute(<adapter>)
	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

========================================
----------------------------------------
========================================
Failed tests:
    Home page

Suite status: FAIL
Total tests: 1
Total failed tests: 1
Total failures: 1
There were failures in galen tests
```


At release-2.3 branch 

```
can@cans-MacBook-Pro-3 ~/galenbug423 $ galen test test.js -Dwebdriver.chrome.driver=/etc/chromedriver               [ruby-2.0.0p648]
========================================
Test: Home page
========================================
Starting ChromeDriver 2.19.346063 (38b35413bd4a486d436a9749e090454bc9ff6708) on port 18260
Only local connections are allowed.

========================================
----------------------------------------
========================================
Suite status: PASS
Total tests: 1
Total failed tests: 0
Total failures: 0
```

**Comment by ishubin** [comment]
@cyildirim Thanks for checking. I will close this issue

**Comment by snehatulsi** [comment]
Thank you so much.
