### ISSUE TITLE
PhantomJS not working

### ISSUE THREAD

**Issue by willihelm** [galenframework/galen#483]
PhantomJS does not work. 

When I start my TestSuite I get the following log output:
`Exception in thread "pool-1-thread-7"
java.lang.NoSuchMethodError: org.openqa.selenium.os.CommandLine.find(Ljava/lang/String;)Ljava/lang/String;
        at org.openqa.selenium.phantomjs.PhantomJSDriverService.findPhantomJS(PhantomJSDriverService.java:232)
        at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:181)
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:104)
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:94)
        at com.galenframework.browser.SeleniumBrowserFactory.getDriver(SeleniumBrowserFactory.java:104)
        at com.galenframework.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:89)
        at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:65)
        at com.galenframework.utils.GalenUtils.createDriver(GalenUtils.java:265)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-internal/Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9-internal/NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-internal/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@9-internal/Method.java:531)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at org.mozilla.javascript.gen._cmd__18._c_createDriver_2(<cmd>:37)
        at org.mozilla.javascript.gen._cmd__18.call(<cmd>)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen._home_galen_git_galenTest_tests_payment_test_js_21._c_anonymous_4(/home/galen/git/galenTest/tests/payment.test.js:81)
        at org.mozilla.javascript.gen._home_galen_git_galenTest_tests_payment_test_js_21.call(/home/galen/git/galenTest/tests/payment.test.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2429)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at org.mozilla.javascript.gen._cmd__17._c_invokeFunc_2(<cmd>:35)
        at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen._cmd__17._c_anonymous_22(<cmd>:280)
        at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
        at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
        at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:606)
        at org.mozilla.javascript.JavaAdapter.access$000(JavaAdapter.java:15)
        at org.mozilla.javascript.JavaAdapter$1.run(JavaAdapter.java:586)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:583)
        at adapter1.execute(<adapter>)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-internal/ThreadPoolExecutor.java:1158)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-internal/ThreadPoolExecutor.java:632)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)`

It may be that the method is not found because its depricated.

**Comment by willihelm** [comment]
I´m using Galen V2.3.3 and PhantomJS V2.1.1.

**Comment by hypery2k** [comment]
Are you using Galen directly from Java or the node executable

**Comment by hypery2k** [comment]
via Maven?

**Comment by willihelm** [comment]
I´m using Galen directly. My TestSuites are written with JS and I use an Ubuntu Server.

**Comment by hypery2k** [comment]
so you manually downloaded the Galen JAR and run it via command line, right?

**Comment by willihelm** [comment]
thats right

**Comment by hypery2k** [comment]
are you using a Galen config to force Galen to use your provided PhantomJS? What OS are you using? Which Java version?

**Comment by willihelm** [comment]
Distro: Ubuntu 16.04.2 LTS with 4.4.0-72-generic
I set the default browser to phantomjs and added the path to the executable in the config file on project level.
Java: openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**Comment by dlockhart** [comment]
I’m experiencing this exact same issue but on OSX Sierra, also with Galen `2.3.3` and Phantom `2.1.1`, Java `1.8.0_73`. Seems potentially [related to this](https://github.com/SeleniumHQ/selenium/issues/3534).

**Comment by nerdkid93** [comment]
I'm guessing this isn't going to get fixed given how long these issues have been here.

**Comment by hypery2k** [comment]
could you try with 2.3.5?

**Comment by nerdkid93** [comment]
Using galenframework@2.3.5, phantomjs-prebuilt@2.1.14, and openjdk@1.8.0_131 results in the exact error mentioned above:
```error
Exception in thread "pool-1-thread-7" java.lang.NoSuchMethodError: 
  org.openqa.selenium.os.CommandLine.find(Ljava/lang/String;)Ljava/lang/String;
  ...
```

**Comment by hypery2k** [comment]
seems like a selenium issue, as from the selenium mailing list I've think PhantomJS isn't working really well with latest selenium versions

@ishubin I think we should drop PhantomJS as supported browser at all and point to headless chrome
