### ISSUE TITLE
a single double quote in the beginning of a rule causes empty gspec error, and hard to find.

### ISSUE THREAD

**Issue by ksiv** [galenframework/galen#525]
@on mobile
        block2.title:
            inside block2 ~ 75 px top
            "above block2.text ~ 45 px

#the quote before above is really hard to find since spec validator fire "gspec should not be empty" error.
#as an rl example - this quote was left after a comment removal.

**Comment by cyildirim** [comment]
Do you mention about `specText should not be empty` error ?  
If it is , Is it good to print spec file line number ?

**Comment by ksiv** [comment]
java.lang.IllegalArgumentException: specText should not be empty

	at com.galenframework.speclang2.specs.SpecReader.read(SpecReader.java:106)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.processSpec(PageSectionProcessor.java:220)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.processObject(PageSectionProcessor.java:191)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.processSection(PageSectionProcessor.java:75)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.process(PageSectionProcessor.java:63)
	at com.galenframework.speclang2.pagespec.PostProcessor.processNode(PostProcessor.java:39)
	at com.galenframework.speclang2.pagespec.PostProcessor.process(PostProcessor.java:33)
