### ISSUE TITLE
Error finding file using load()

### ISSUE THREAD

**Issue by axelbarfod1** [galenframework/galen#549]
Hi, i'm having issues with the load(), it is not finding the file. I know the path is correct becuase I can navigate to it when using the require, below is the load and the route.

       load('../../ui_galen/pages/HomePage.js');
`//require('../../ui_galen/pages/HomePage.js');`

These are the following paths I also tried with no success:

- '../test/test-e2e/ui_galen/pages/HomePage.js'
- './test/test-e2e/ui_galen/pages/HomePage.js'

Below is the error im im getting
 
`Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Could not load script: ../../ui_galen/pages/HomePage.js
	at com.galenframework.GalenMain.execute(GalenMain.java:60)
	at com.galenframework.GalenMain.main(GalenMain.java:78)
Caused by: java.lang.RuntimeException: Could not load script: ../../ui_galen/pages/HomePage.js
	at com.galenframework.javascript.JsFunctionLoad.load(JsFunctionLoad.java:76)
	at com.galenframework.javascript.JsFunctionLoad.call(JsFunctionLoad.java:65)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._Users_abarfod_workspace_fury_identity_validation_frontend___test_test_e2e_ui_galen_tests_HomePage_test_js_20._c_script_0(/Users/abarfod/workspace/fury_identity-validation-frontend/./test/test-e2e/ui_galen/tests/HomePage.test.js:1)
	at org.mozilla.javascript.gen._Users_abarfod_workspace_fury_identity_validation_frontend___test_test_e2e_ui_galen_tests_HomePage_test_js_20.call(/Users/abarfod/workspace/fury_identity-validation-frontend/./test/test-e2e/ui_galen/tests/HomePage.test.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
	at org.mozilla.javascript.gen._Users_abarfod_workspace_fury_identity_validation_frontend___test_test_e2e_ui_galen_tests_HomePage_test_js_20.call(/Users/abarfod/workspace/fury_identity-validation-frontend/./test/test-e2e/ui_galen/tests/HomePage.test.js)
	at org.mozilla.javascript.gen._Users_abarfod_workspace_fury_identity_validation_frontend___test_test_e2e_ui_galen_tests_HomePage_test_js_20.exec(/Users/abarfod/workspace/fury_identity-validation-frontend/./test/test-e2e/ui_galen/tests/HomePage.test.js)
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1110)
	at com.galenframework.javascript.GalenJsExecutor.eval(GalenJsExecutor.java:99)
	at com.galenframework.runner.JsTestCollector.execute(JsTestCollector.java:63)
	at com.galenframework.actions.GalenActionTest.runTestFiles(GalenActionTest.java:103)
	at com.galenframework.actions.GalenActionTest.execute(GalenActionTest.java:87)
	at com.galenframework.GalenMain.execute(GalenMain.java:58)
	... 1 more
Caused by: org.mozilla.javascript.EcmaError: ReferenceError: "require" is not defined.`

Attached a screenshot of the project structure

![screen shot 2017-12-28 at 18 05 46](https://user-images.githubusercontent.com/32651536/34423337-018cb7b8-ebfa-11e7-99d0-a9a5029771ed.png)

**Comment by axelbarfod1** [comment]
I found the problem, on the JS homePage im using a require, which it isn´t liking. On the HomePage I want to import another JS file how can we do that?

**Comment by t2hv33** [comment]
Because pages/HomePage.js is declare page object is not correctly
