### ISSUE TITLE
Cannot set to a different browser via command line

### ISSUE THREAD

**Issue by zfolwick** [galenframework/galen#559]
```
galen.bat check homepage.gspec --config "..\galen.chrome.config" --url http://localhost:3000/#/ --size 1024x768 --htmlreport
reports
========================================
Test: homepage.gspec
========================================
Feb 20, 2018 6:30:36 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
        at com.google.common.base.Preconditions.checkState(Preconditions.java:754)
        at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:124)
        at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
        at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
        at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:339)
        at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:147)
        at com.galenframework.browser.SeleniumBrowserFactory.getDriver(SeleniumBrowserFactory.java:98)
        at com.galenframework.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:89)
        at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:65)
        at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:73)
        at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

the issue appears to be in `galen/galen-core/src/main/java/com/galenframework/browser/SeleniumBrowserFactory.java`, where the chromedriver is instantiated.  Is this the correct way to add chrome?  According to the docs and research, I'm getting this working:
```
        String driverName = "webdriver.chrome.driver";
        String driverPath = basedir + "chromedriver_win32\\chromedriver.exe";
        System.setProperty(driverName, driverPath);
        Webdriver d = new ChromeDriver();
```

I have not built locally to test on this project, but in trying to get galen working, I'm running into this issue on the command line in windows 10 for ALL BROWSERS that are not firefox.

**Comment by ishubin** [comment]
It tells you in the Exception that you also need to provide a system property for path to chromedriver binary. Here is how you can do it:
```
galen.bat check homepage.gspec --config "..\galen.chrome.config" --url http://localhost:3000/#/ --size 1024x768 --htmlreport reports -Dwebdriver.chrome.driver=some\path\to\your\chromedriver.exe
```
Obvously you need to replace the above with  a proper path, depending on where you have downloaded it

**Comment by zfolwick** [comment]
even if my chromedriver was put on my PATH?

**Comment by ishubin** [comment]
Sorry for late reply. It is hard for me to tell what is wrong with your galen config file. The only thing that comes to mind is that you might be missing `$.` prefix for the system properties inside `galen.chrome.config`. The thing with all those `-Dwebdriver.chrome.driver` properties is that it has to be set as a system property. That is why in galen config we added some syntactic sugar in the form of `$.` prefix. Anything that goes with that prefix will be set as a system property.
That's all I can think of so far
