### ISSUE TITLE
Cannot parse range value: ""(..)

### ISSUE THREAD

**Issue by shikthak** [galenframework/galen#572]
I have created a specification file **adminspecs** and trying to run it with Java and Junit code, while executing the same getting error **Cannot parse range value: ""(..)**. Below I have posted code, exception and spec file content. I am unable to figure out the cause for the exception.

PS: I have tested same code with another spec file - loginspecs and that works fine.

**Junit code with Java:**

      @Test

	    public void adminPageLayoutTest() throws IOException
	    {

	        //Create a layoutReport object

	        //checkLayout function checks the layout and returns a LayoutReport object
	        LayoutReport layoutReport = Galen.checkLayout(driver, "src/test/specs/adminpage.gspec", Arrays.asList("desktop"));

	        //Create a tests list
	        List<GalenTestInfo> tests = new LinkedList<GalenTestInfo>();

	        //Create a GalenTestInfo object
	        GalenTestInfo test = GalenTestInfo.fromString("adminpage layout");

	        //Get layoutReport and assign to test object
	        test.getReport().layout(layoutReport, "check adminpage layout");

	        //Add test object to the tests list
	        tests.add(test);

	        //Create a htmlReportBuilder object
	        HtmlReportBuilder htmlReportBuilder = new HtmlReportBuilder();

	        //Create a report under /target folder based on tests list
	        htmlReportBuilder.build(tests, "target");

	        //If layoutReport has errors Assert Fail
	        if (layoutReport.errors() > 0)
	        {
	            Assert.fail("Layout test failed");
	        }
	    }

**Exception:**
adminPageLayoutTest(com.nice.galenautomation.GalenFirstTest)  Time elapsed: 13.744 sec  <<< ERROR!
com.galenframework.parser.SyntaxException: Cannot parse range value: ""
    in src/test/specs/adminpage.gspec:16
	at com.galenframework.parser.ExpectRangeValue.read(ExpectRangeValue.java:59)
	at com.galenframework.parser.ExpectRange.read(ExpectRange.java:42)
	at com.galenframework.parser.ExpectRange.read(ExpectRange.java:25)
	at com.galenframework.parser.ExpectLocations.read(ExpectLocations.java:34)
	at com.galenframework.parser.ExpectLocations.read(ExpectLocations.java:27)
	at com.galenframework.speclang2.specs.SpecInsideProcessor.process(SpecInsideProcessor.java:49)
	at com.galenframework.speclang2.specs.SpecReader.read(SpecReader.java:115)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.processSpec(PageSectionProcessor.java:220)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.processObject(PageSectionProcessor.java:191)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.processSection(PageSectionProcessor.java:75)
	at com.galenframework.speclang2.pagespec.PageSectionProcessor.process(PageSectionProcessor.java:63)
	at com.galenframework.speclang2.pagespec.PostProcessor.processNode(PostProcessor.java:39)
	at com.galenframework.speclang2.pagespec.PostProcessor.process(PostProcessor.java:33)
	at com.galenframework.speclang2.pagespec.PageSpecReader.read(PageSpecReader.java:62)
	at com.galenframework.speclang2.pagespec.PageSpecReader.read(PageSpecReader.java:45)
	at com.galenframework.api.Galen.checkLayout(Galen.java:68)
	at com.galenframework.api.Galen.checkLayout(Galen.java:59)
	at com.galenframework.api.Galen.checkLayout(Galen.java:154)
	at com.galenframework.api.Galen.checkLayout(Galen.java:128)
	at com.nice.galenautomation.GalenFirstTest.adminPageLayoutTest(GalenFirstTest.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.galenframework.specs.RangeValue.parseRangeValue(RangeValue.java:164)
	at com.galenframework.parser.ExpectRangeValue.read(ExpectRangeValue.java:56)
	... 50 more
Results :

Tests in error: 
  adminPageLayoutTest(com.nice.galenautomation.GalenFirstTest): Cannot parse range value: ""(..)

**adminspecs file**
@objects
  header-pm      css    .main-title
  menu-new       id     menubar_newitem
  menu-config    id     menubar_configurations
  menu-hier        id     menubar_hierarchies     
  menu-dp         id     menubar_data-processing
  menu-wrkflw    id     menubar_workflows
  menu-coach     id     menubar_coaching
  menu-system    id     menubar_system-configurations
  adminportlet    id     p_p_id_nice_admin_portlet_WAR_platformuseradminportlet_
  
= Admin header = 
	@on desktop
	   header-pm:
		         visible
			
= Admin Body = 
	@on desktop
	   adminportlet:
			   visible

**Comment by cyildirim** [comment]
I have tried with the` adminspecs.gspec`. I didn't get any error with the right indentation. Could you share the URL and `adminspecs.gspecs` file with the exact indentation?
