### ISSUE TITLE
Get Java 10 Compatibility

### ISSUE THREAD

**Issue by sglahn** [galenframework/galen#573]
Running Galen with Java 10 results in

`java.lang.RuntimeException: java.lang.UnsupportedOperationException: Cannot define class using reflection
	at com.galenframework.browser.SeleniumGridBrowserFactory.openBrowser(SeleniumGridBrowserFactory.java:53)
	at com.galenframework.browser.SeleniumBrowserFactory.createSeleniumGridBrowser(SeleniumBrowserFactory.java:81)
	at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:62)
	at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:73)
	at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Unavailable.defineClass(ClassInjector.java:821)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:185)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:187)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:120)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4456)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4446)
	at org.openqa.selenium.remote.Augmenter.performAugmentation(Augmenter.java:145)
	at org.openqa.selenium.remote.Augmenter.create(Augmenter.java:63)
	at org.openqa.selenium.remote.BaseAugmenter.augment(BaseAugmenter.java:110)
	at com.galenframework.browser.SeleniumGridBrowserFactory.openBrowser(SeleniumGridBrowserFactory.java:49)
	... 9 more
Caused by: java.lang.IllegalArgumentException: Unknown Java version: 10
	at net.bytebuddy.ClassFileVersion.ofJavaVersion(ClassFileVersion.java:135)
	at net.bytebuddy.ClassFileVersion$VersionLocator$ForJava9CapableVm.locate(ClassFileVersion.java:357)
	at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:147)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:301)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:290)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.<clinit>(ClassInjector.java:70)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:184)`

Upgrading the Selenium version from 3.8.1 to 3.11.0 fixes the problem.

**Comment by stefanneuhaus** [comment]
This seems to be fixed by #575.
@ishubin Could you make a rough estimate when the next version will be released?

**Comment by ishubin** [comment]
@stefanneuhaus I have just released it in 2.3.7 version. Sorry for the delay
