### ISSUE TITLE
Unable to galen on Android chrome

### ISSUE THREAD

**Issue by kgurijala** [galenframework/galen#578]
**I am trying to run Galen tests on real android device (Samsung Galaxy S6) but am failing**

**Here is my driver code
    var driver = createGridDriver("http://127.0.0.1:8001/wd/hub", {
      browser: "chrome",
      desiredCapabilities: {
        platformName: "Android",
        deviceName: "Samsung",
        automationName: "appium",
        bundleId : "com.android.chrome"
      }
    });**

**Below is my error log on Galen run command**

> node ./node_modules/galenframework/bin/galen test ./src/galen.tests.js --config ./config/galen.config --htmlreport reports/galen

========================================
Test: Test on mobile
========================================
org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities {automationName: appium, browserName: chrome, bundleId: com.samsung.chrome, deviceName: Samsung, platformName: Android}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'maclb068206', ip: 'fe80:0:0:0:806:2cc8:73e8:22c7%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_161'
Driver info: driver.version: RemoteWebDriver (<cmd>#54)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.mozilla.javascript.gen._cmd__18._c_createGridDriver_4(<cmd>:54)
	at org.mozilla.javascript.gen._cmd__18.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._Users_a626283_Code_Test_us_release1___src_galen_tests_js_20._c_anonymous_3(/Users/a626283/Code/Test/us-release1/./src/galen.tests.js:46)
	at org.mozilla.javascript.gen._Users_a626283_Code_Test_us_release1___src_galen_tests_js_20.call(/Users/a626283/Code/Test/us-release1/./src/galen.tests.js)
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2429)
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
	at org.mozilla.javascript.gen._cmd__17._c_invokeFunc_2(<cmd>:33)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen._cmd__17._c_anonymous_22(<cmd>:280)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
	at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
	at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:606)
	at org.mozilla.javascript.JavaAdapter.access$000(JavaAdapter.java:15)
	at org.mozilla.javascript.JavaAdapter$1.run(JavaAdapter.java:586)
	at org.mozilla.javascript.Context.call(Context.java:489)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
	at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:583)
	at adapter3.execute(<adapter>)
	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities {automationName: appium, browserName: chrome, bundleId: com.samsung.chrome, deviceName: Samsung, platformName: Android}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'maclb068206', ip: 'fe80:0:0:0:806:2cc8:73e8:22c7%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_161'
Driver info: driver.version: RemoteWebDriver
	at com.galenframework.browser.SeleniumGridBrowserFactory.openBrowser(SeleniumGridBrowserFactory.java:53)
	at com.galenframework.utils.GalenUtils.createGridDriver(GalenUtils.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	... 31 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities {automationName: appium, browserName: chrome, bundleId: com.samsung.chrome, deviceName: Samsung, platformName: Android}
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'maclb068206', ip: 'fe80:0:0:0:806:2cc8:73e8:22c7%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_161'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:86)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at com.galenframework.browser.SeleniumGridBrowserFactory.openBrowser(SeleniumGridBrowserFactory.java:48)
	... 37 more

========================================
----------------------------------------
========================================
Failed tests:
    Test on mobile

Suite status: FAIL
Total tests: 1
Total failed tests: 1
Total failures: 1
There were failures in galen tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NetBenefits@3.0.0 galen: `node ./node_modules/galenframework/bin/galen test ./src/galen.tests.js --config ./config/galen.config --htmlreport reports/galen`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the NetBenefits@3.0.0 galen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Here is a part my log on appium:**

[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] ProxyRequestError: Could not proxy command to remote server. Original error: Error: read ECONNRESET
[Chromedriver]     at JWProxy.proxy$ (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)
[Chromedriver]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[Chromedriver]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[Chromedriver]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[Chromedriver]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

Please do the needful.

**Comment by cyildirim** [comment]
- Are you able to run the test from directly java+appium through selenium grid with same capabilities?
- Which appium version you are using?

**Comment by dacotto1984** [comment]
Im having the same issue.  Where you able to find the solution?
