### ISSUE TITLE
Getting error trying to dump with galen test

### ISSUE THREAD

**Issue by mtopcu** [galenframework/galen#581]
Hi,
I have created a galen test file to run my gspec file. It is working with "check" command but not working with "dump". I have shared my all codes. Do you have any idea? 

Thanks.

*** home.gspec file ***

```
@objects
	header	id bnw-header
	d3	css .gwt-module

= Compare the objects =
		header:
			image file home-dump/objects/header.png, error %4

		d3:
			image file home-dump/objects/d3.png, error %4
```

*** runtest.test file ***

```
@@ set
	gridUrl    http://localhost:4444/wd/hub
	stageUrl     https://www-stage-admin.sonymobile.com/test/galen-pages/
	prodUrl     https://www.sonymobile.com/test/galen-pages/
	size     1024x768

@@ parameterized
	| module |
	| d3     |

Comparing Test with ${module} with ${size} size.
	selenium grid ${gridUrl} --browser chrome --page ${stageUrl}${module} --size ${size}
		dump home.gspec --export home-dump
```

*** The result ***

```
TRSEUISTMAC033:comparing trtopcmu$ galen test runtest.test
========================================
Test: Comparing Test with d3 with 1024x768 size.
========================================
Jun 12, 2018 10:39:42 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
dump home.gspec --export home-dump
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at com.galenframework.api.GalenPageDump.exportAsHtml(GalenPageDump.java:156)
	at com.galenframework.api.GalenPageDump.dumpPage(GalenPageDump.java:115)
	at com.galenframework.api.GalenPageDump.dumpPage(GalenPageDump.java:74)
	at com.galenframework.suite.actions.GalenPageActionDumpPage.execute(GalenPageActionDumpPage.java:59)
	at com.galenframework.runner.GalenPageRunner.executeAction(GalenPageRunner.java:84)
	at com.galenframework.runner.GalenPageRunner.run(GalenPageRunner.java:76)
	at com.galenframework.runner.GalenBasicTestRunner.runTest(GalenBasicTestRunner.java:76)
	at com.galenframework.tests.GalenBasicTest.execute(GalenBasicTest.java:55)
	at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
	at com.galenframework.TestRunnable.run(TestRunnable.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

========================================
----------------------------------------
========================================
Failed tests:
    Comparing Test with d3 with 1024x768 size.

Suite status: FAIL
Total tests: 1
Total failed tests: 1
Total failures: 1
There were failures in galen tests
```

**Comment by mtopcu** [comment]
I have just found my problem. I should use "--name <parameter>" with dump command. 

Like: dump home.gspec --name SeleniumGrid Galen Tests --export home-dump

Thank you anyway. :)
