### ISSUE TITLE
Nullpointer Excpetion while trying to create gspec file using new feature Spec Generator in Release 2.4

### ISSUE THREAD

**Issue by arulrajbt** [galenframework/galen#597]
Getting Nullpointer exception while calling the method generateSpecSections with PageSpecGenerationResult object as a parameter.
<snip>
java.lang.NullPointerException
	at com.galenframework.generator.model.GmPageSpec.lambda$null$51(GmPageSpec.java:75)
	at com.galenframework.generator.PageItemNode.visitTree(PageItemNode.java:80)
	at com.galenframework.generator.PageItemNode.visitTree(PageItemNode.java:82)
	at com.galenframework.generator.model.GmPageSpec.lambda$create$52(GmPageSpec.java:61)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.galenframework.generator.model.GmPageSpec.create(GmPageSpec.java:61)
	at com.galenframework.generator.SpecGenerator.generateSpecSections(SpecGenerator.java:228)
</snip>

**Comment by arulrajbt** [comment]
I would like to generate a spec file automatically using the 'Spec Generator' feature in 2.4 by passing the PageDump json file as an input.

But i'm getting Null pointer exception while calling the method generateSpecSections in SpecGenerator.

Please help me here.

**Comment by ishubin** [comment]
It is not really clear how to reproduce this issue. Could you please share the pagedump and exact command that reproduces this issue?

**Comment by arulrajbt** [comment]
Attached the pagedump json file for reference.

[page.zip](https://github.com/galenframework/galen/files/2632382/page.zip)

Command that throws Nullpointer exception
specGenerator.generateSpecSections(result)

**Comment by arulrajbt** [comment]
Please let me know if you need any other details

**Comment by arulrajbt** [comment]
Thank you ishubin.

May i know the issue behind this please.

**Comment by ishubin** [comment]
I have pushed a fix in the master branch. Tomorrow will try to make a minor release once I fix another issue.
I couldn't reproduce this issue with my own simplified page dump. But in your example it was failing on these two elements `fleethome-ourapproach-container` and `fleethome-ourapproach-container-img`.
Maybe the reason is that they are located off-screen as `fleethome-ourapproach-container` was located with -8 left position, but I am not sure

**Comment by shankar4a1** [comment]
Hi Team, 
I am encountering the similar issue when am trying to generate spec file.  I have attached log below. Can some one please help. Have attached page dump in zip format

>galen generate "LayoutTest/galen-sample-tests-master/dumps/homepage/page.json" --export "LayoutTest/galen-sample-tests-master/specs/homePageNew.gspec" --no-galen-extras
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.get(String)" because "jsonTree" is null
        at com.galenframework.GalenMain.execute(GalenMain.java:60)
        at com.galenframework.GalenMain.main(GalenMain.java:78)
Caused by: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.get(String)" because "jsonTree" is null
        at com.galenframework.generator.PageItemJsonMapper.loadItems(PageItemJsonMapper.java:31)
        at com.galenframework.generator.SpecGenerator.generate(SpecGenerator.java:39)
        at com.galenframework.actions.GalenActionGenerate.execute(GalenActionGenerate.java:42)
        at com.galenframework.GalenMain.execute(GalenMain.java:58)
        ... 1 more
[homepage.zip](https://github.com/galenframework/galen/files/9047003/homepage.zip)
