### ISSUE TITLE
freemarker.core.InvalidReferenceException: Expression node.name is undefined on line 15, column 61 in report-main

### ISSUE THREAD

**Issue by dzharii** [galenframework/galen#66]
When I've tried to run a spec on galen-bin-1.0.0, I've got the following exception inside HTML report 

`freemarker.core.InvalidReferenceException: Expression node.name is undefined on line 15, column 61 in report-main`

Commandline:

> galen check homepage.spec --url "http://validator.w3.org/"  --size "1024x768" --htmlreport "htmlreport-dir"

homepage.spec:

```
header
    height: 35 to 45px

```

system:

> java version "1.7.0_40"
> Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
> Java HotSpot(TM) Client VM (build 24.0-b56, mixed mode, sharing)
> 
> OS Name:                   Microsoft Windows 7 Enterprise 
> OS Version:                6.1.7601 Service Pack 1 Build 7601
> System Type:               x64-based PC
> Processor(s):              1 Processor(s) Installed.
> System Locale:             ru;Russian
> Input Locale:              en-us;English (United States)
> Time Zone:                 (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
> Total Physical Memory:     8,065 MB
> Available Physical Memory: 2,964 MB

Error:

```
Expression node.name is undefined on line 15, column 61 in report-main.
The problematic instruction:
----------
==> ${node.name?html} [on line 15, column 59 in report-main]
 in user-directive report_node [on line 113, column 17 in report-main]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression node.name is undefined on line 15, column 61 in report-main.
    at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:125)
    at freemarker.core.Expression.getStringValue(Expression.java:118)
    at freemarker.core.Expression.getStringValue(Expression.java:93)
    at freemarker.core.StringBuiltins$StringBuiltIn._getAsTemplateModel(StringBuiltins.java:71)
    at freemarker.core.Expression.getAsTemplateModel(Expression.java:89)
    at freemarker.core.Expression.getStringValue(Expression.java:93)
    at freemarker.core.DollarVariable.accept(DollarVariable.java:76)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.MixedContent.accept(MixedContent.java:92)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.Macro$Context.runMacro(Macro.java:172)
    at freemarker.core.Environment.visit(Environment.java:614)
    at freemarker.core.UnifiedCall.accept(UnifiedCall.java:106)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:179)
    at freemarker.core.Environment.visit(Environment.java:428)
    at freemarker.core.IteratorBlock.accept(IteratorBlock.java:102)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:79)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.MixedContent.accept(MixedContent.java:92)
    at freemarker.core.Environment.visit(Environment.java:221)
    at freemarker.core.Environment.process(Environment.java:199)
    at freemarker.template.Template.process(Template.java:259)
    at net.mindengine.galen.reports.HtmlReportBuilder.exportTestReport(HtmlReportBuilder.java:69)
    at net.mindengine.galen.reports.HtmlReportBuilder.build(HtmlReportBuilder.java:48)
    at net.mindengine.galen.GalenMain.createHtmlReport(GalenMain.java:372)
    at net.mindengine.galen.GalenMain.createAllReports(GalenMain.java:366)
    at net.mindengine.galen.GalenMain.runTestsInThreads(GalenMain.java:314)
    at net.mindengine.galen.GalenMain.runTests(GalenMain.java:254)
    at net.mindengine.galen.GalenMain.performCheck(GalenMain.java:173)
    at net.mindengine.galen.GalenMain.execute(GalenMain.java:79)
    at net.mindengine.galen.GalenMain.main(GalenMain.java:192)




```

**Comment by ElenaWei** [comment]
@ishubin Hi, I know it's too long time ago when you fixed this issue. Your professional skills inspired me. Recently our team is working on a legacy system which was developed in 2007. Now I am facing the same problems as described above, if luckily you see this message, can you please share me the solution? By my thinking, it should be the version problems, since this issue happened after we upgrade the java to 10, and mySQL to 8.  You can email me if you want, my Email address: weiyaorui@gmail.com. Thank you very much!

**Comment by ishubin** [comment]
@ElenaWei Hi! Well I don't know what is the particular problem in your case, but for this specific bug it was fixed by this line https://github.com/galenframework/galen/commit/6b417c1fe93c7fa3e0651e382142430754e86453#diff-263299840f795de90632a744837c35f8R15
As you can see it was missing the check whether node.name was actually set. Since it was null it could not render the content for it. If I remember correctly this is a default behavior of freemarker

**Comment by ElenaWei** [comment]
@ishubin Thank you very much for the response and explanation. Finally, I fixed the bugs yesterday. You are right, it caused by the null values pass into Freemarker template.  Thanks again.
